@extends('asset-rentals.public.layout')
@section('title','Status Reservasi')
@section('content')
<div class="container py-5 status-shell">@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif<div class="card border-0 shadow-sm overflow-hidden"><div class="card-body p-4 p-md-5"><div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><span class="badge bg-label-{{$reservation->status_color}} mb-2">{{$reservation->status_label}}</span><h2 class="fw-bold mb-1" id="bookingCode">{{$reservation->booking_code}}</h2><p class="text-muted mb-2">Simpan kode tiket dan alamat halaman ini untuk memeriksa perkembangan reservasi.</p><button type="button" class="btn btn-sm btn-outline-primary" onclick="navigator.clipboard.writeText(document.getElementById('bookingCode').textContent.trim());this.innerHTML='<i class=&quot;bx bx-check me-1&quot;></i>Tersalin'"><i class="bx bx-copy me-1"></i>Salin Kode Tiket</button></div><span class="brand-mark fs-4"><i class="bx bx-calendar-check"></i></span></div><div class="d-flex flex-wrap gap-2 mb-3">
<a href="{{route('public.asset-rentals.receipt',$reservation->public_token)}}" class="btn btn-primary"><i class="bx bx-download me-1"></i>Unduh Kwitansi Booking (PDF)</a>
@if($setting->manager_whatsapp_number)<a target="_blank" rel="noopener noreferrer" href="https://wa.me/{{$setting->manager_whatsapp_number}}?text={{urlencode('Halo Admin, saya '.$reservation->full_name.' ingin konfirmasi booking '.$reservation->booking_code.' untuk '.$reservation->asset->name.'. Status: '.$reservation->status_label.'. '.route('public.asset-rentals.status',$reservation->public_token))}}" class="btn btn-success"><i class="bx bxl-whatsapp me-1"></i>Hubungi Admin via WhatsApp</a>@endif
</div><p class="text-muted small mb-4">Unduh dan bawa kwitansi saat datang. Booking berlaku setelah pembayaran dikonfirmasi admin.</p>
<div class="row g-3 mb-4"><div class="col-md-6"><div class="p-3 bg-light rounded"><small class="text-muted">Fasilitas</small><strong class="d-block">{{$reservation->asset->name}}</strong></div></div><div class="col-md-6"><div class="p-3 bg-light rounded"><small class="text-muted">Tanggal dan waktu</small><strong class="d-block">{{$reservation->rental_date->translatedFormat('d F Y')}} · {{substr($reservation->start_time,0,5)}}–{{substr($reservation->end_time,0,5)}}</strong></div></div><div class="col-md-6"><div class="p-3 bg-light rounded"><small class="text-muted">Pemohon</small><strong class="d-block">{{$reservation->full_name}}</strong></div></div><div class="col-md-6"><div class="p-3 bg-light rounded"><small class="text-muted">Total pembayaran</small><strong class="d-block text-primary">Rp {{number_format($reservation->total_amount,0,',','.')}}</strong></div></div></div>@include('asset-rentals.public.tracking')
@if($reservation->admin_note)<div class="alert alert-warning"><strong>Catatan pengelola:</strong><div>{{$reservation->admin_note}}</div></div>@endif
@if(in_array($reservation->status,['awaiting_payment','revision']))<div class="border rounded p-4"><h5 class="fw-bold">Pembayaran Reservasi</h5><p class="mb-2">Transfer ke <strong>{{$setting->bank_name}} — {{$setting->bank_account}}</strong><br>A.n. {{$setting->bank_account_name}}</p>@if($reservation->payment_due_at)<small class="text-danger d-block mb-3">Batas pembayaran: {{$reservation->payment_due_at->translatedFormat('d F Y, H:i')}} WIB</small>@endif<form method="POST" enctype="multipart/form-data" action="{{route('public.asset-rentals.payment',$reservation->public_token)}}">@csrf<label class="form-label">Unggah bukti pembayaran (PDF/JPG/PNG)</label><div class="input-group"><input type="file" name="payment_proof" accept=".pdf,.jpg,.jpeg,.png" class="form-control" required><button class="btn btn-primary">Kirim Bukti</button></div></form></div>@elseif($reservation->status==='payment_uploaded')<div class="alert alert-info"><i class="bx bx-time-five me-1"></i>Bukti pembayaran sudah diterima dan sedang diverifikasi pengelola.</div>@elseif($reservation->status==='confirmed')<div class="alert alert-success"><i class="bx bx-check-circle me-1"></i><strong>Reservasi dikonfirmasi.</strong> Tunjukkan kode reservasi ini saat menggunakan fasilitas.</div>@endif<div class="d-flex flex-wrap gap-2 mt-4"><a href="{{route('public.asset-rentals.index')}}" class="btn btn-outline-primary">Lihat Fasilitas Lain</a>@if($setting->manager_whatsapp)<a target="_blank" href="https://wa.me/{{$setting->manager_whatsapp_number}}?text={{urlencode('Halo, saya ingin menanyakan reservasi '.$reservation->booking_code)}}" class="btn btn-success"><i class="bx bxl-whatsapp me-1"></i>Hubungi Pengelola</a>@endif</div></div></div></div>
@endsection