@php
 $rateRows=collect(old('rental_rates',$asset?->rentalRates?->map(fn($rate)=>['start_time'=>substr($rate->start_time,0,5),'end_time'=>substr($rate->end_time,0,5),'hourly_rate'=>$rate->hourly_rate])->all()?:[['start_time'=>'07:00','end_time'=>'21:00','hourly_rate'=>$asset?->hourly_rate??0]]));
@endphp
<div class="row g-3">
 <div class="col-md-8"><label class="form-label">Nama Aset <span class="text-danger">*</span></label><input name="name" class="form-control" value="{{old('name',$asset?->name)}}" required></div>
 <div class="col-md-4"><label class="form-label">Jenis <span class="text-danger">*</span></label><select name="type" class="form-select" required>@foreach(['ruangan','kendaraan','peralatan','lainnya'] as $type)<option value="{{$type}}" @selected(old('type',$asset?->type)===$type)>{{ucfirst($type)}}</option>@endforeach</select></div>
 <div class="col-md-8"><label class="form-label">Lokasi <span class="text-danger">*</span></label><input name="location" class="form-control" value="{{old('location',$asset?->location)}}" required></div>
 <div class="col-md-4"><label class="form-label">Kapasitas</label><div class="input-group"><input type="number" min="1" name="capacity" class="form-control" value="{{old('capacity',$asset?->capacity)}}"><span class="input-group-text">orang</span></div></div>
 <div class="col-12"><label class="form-label">Fasilitas</label><textarea name="facilities" rows="2" class="form-control">{{old('facilities',$asset?->facilities)}}</textarea></div>
 <div class="col-12"><label class="form-label">Deskripsi</label><textarea name="description" rows="3" class="form-control">{{old('description',$asset?->description)}}</textarea></div>
 <div class="col-12"><label class="form-label">{{$editing?'Tambahkan Foto':'Foto'}} <small class="text-muted">(maks. 10 file, masing-masing 5 MB)</small></label><input type="file" name="images[]" multiple accept="image/*" class="form-control">@if($editing)<div class="form-text">Foto baru ditambahkan tanpa menghapus foto lama.</div>@endif</div>
 <div class="col-12"><div class="p-3 border rounded bg-light rental-editor">
  <div class="form-check form-switch mb-3"><input type="checkbox" class="form-check-input rentable-toggle" name="is_rentable" value="1" id="isRentable{{$asset?->id??'New'}}" @checked(old('is_rentable',$asset?->is_rentable??false))><label class="form-check-label fw-semibold" for="isRentable{{$asset?->id??'New'}}">Fasilitas dapat disewa oleh umum</label></div>
  <div class="rental-fields">
   <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-2"><div><label class="form-label fw-semibold mb-0">Tarif berdasarkan rentang waktu</label><small class="d-block text-muted">Setiap aset dapat memiliki tarif berbeda. Rentang tidak boleh tumpang tindih.</small></div><button type="button" class="btn btn-sm btn-outline-primary add-rate"><i class="bx bx-plus me-1"></i>Tambah Tarif</button></div>
   <div class="rate-rows">@foreach($rateRows as $index=>$rate)<div class="rate-row row g-2 align-items-end mb-2"><div class="col-md-3"><label class="form-label small">Mulai</label><input type="time" name="rental_rates[{{$index}}][start_time]" value="{{$rate['start_time']}}" class="form-control rate-start"></div><div class="col-md-3"><label class="form-label small">Selesai</label><input type="time" name="rental_rates[{{$index}}][end_time]" value="{{$rate['end_time']}}" class="form-control rate-end"></div><div class="col-md-5"><label class="form-label small">Harga per jam</label><div class="input-group"><span class="input-group-text">Rp</span><input type="number" min="0" step="1000" name="rental_rates[{{$index}}][hourly_rate]" value="{{$rate['hourly_rate']}}" class="form-control rate-price"></div></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger w-100 remove-rate" title="Hapus tarif"><i class="bx bx-trash"></i></button></div></div>@endforeach</div>
   <div class="row g-3 mt-1"><div class="col-md-6"><label class="form-label">Durasi booking minimal</label><div class="input-group"><input type="number" min="1" max="24" name="rental_min_hours" class="form-control" value="{{old('rental_min_hours',$asset?->rental_min_hours??1)}}"><span class="input-group-text">jam</span></div></div><div class="col-md-6"><label class="form-label">Durasi booking maksimal</label><div class="input-group"><input type="number" min="1" max="24" name="rental_max_hours" class="form-control" value="{{old('rental_max_hours',$asset?->rental_max_hours??8)}}"><span class="input-group-text">jam</span></div></div><div class="col-12"><div class="form-text"><i class="bx bx-info-circle me-1"></i>Jika maksimal diisi 1, pemesan hanya dapat memilih 1 jam. Isi sesuai durasi terpanjang yang diizinkan, misalnya 12 jam.</div></div></div>
  </div>
 </div></div>
 <div class="col-12"><div class="form-check form-switch"><input type="checkbox" class="form-check-input" name="is_public" value="1" id="isPublic{{$asset?->id??'New'}}" @checked(old('is_public',$asset?->is_public??true))><label class="form-check-label" for="isPublic{{$asset?->id??'New'}}">Tampilkan aset di halaman publik</label></div></div>
</div>