@extends('layouts.master')
@section('title','Bagikan Folder')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><a href="{{route('documents.index',['folder'=>$folder->id,'bidang'=>$folder->bidang])}}" class="small"><i class="bx bx-arrow-back"></i> Kembali ke folder</a><h4 class="fw-bold mt-2 mb-1">Bagikan “{{$folder->name}}”</h4><p class="text-muted mb-0">Atur pengguna yang dapat melihat atau berkontribusi ke folder beserta seluruh subfoldernya.</p></div><span class="badge bg-label-primary fs-6"><i class="bx bx-group me-1"></i>{{$folder->permissions->count()}} pengguna</span></div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif
<div class="row g-4"><div class="col-lg-5"><div class="card border-0 shadow-sm"><div class="card-header"><h5 class="mb-1">Tambah Pengguna</h5><small class="text-muted">Cari seluruh akun tanpa batasan bidang atau role.</small></div><div class="card-body"><form method="POST" action="{{route('documents.folder.sharing.store',$folder)}}">@csrf<input type="hidden" name="user_id" id="shareUserId"><label class="form-label">Nama, NIP/NIK, atau username</label><div class="position-relative"><input type="search" id="shareUserSearch" class="form-control" autocomplete="off" placeholder="Ketik minimal 2 karakter..."><div id="shareSearchResults" class="list-group position-absolute w-100 shadow-lg d-none share-user-results"></div></div><div id="selectedUser" class="alert bg-label-primary mt-3 d-none mb-3"></div><label class="form-label">Hak Akses</label><select name="permission" class="form-select" required><option value="contributor">Kontributor — lihat, upload, buat folder, dan versi baru</option><option value="viewer">Pelihat — hanya melihat dan mengunduh</option></select><button class="btn btn-primary w-100 mt-3" id="shareSubmit" disabled><i class="bx bx-user-plus me-1"></i>Bagikan Folder</button></form></div></div><div class="alert alert-info small mt-3"><strong>Catatan:</strong> kontributor tidak dapat menghapus folder, file, mengubah privasi, atau membagikan ulang. Akses ini otomatis berlaku pada seluruh subfolder.</div></div>
<div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-header"><h5 class="mb-1">Pengguna yang Memiliki Akses</h5><small class="text-muted">Pemilik folder selalu memiliki akses penuh.</small></div><div class="list-group list-group-flush"><div class="list-group-item p-3 d-flex align-items-center gap-3"><span class="avatar"><span class="avatar-initial rounded-circle bg-label-success">{{strtoupper(substr($folder->user?->name?:'P',0,1))}}</span></span><div class="flex-grow-1"><strong>{{$folder->user?->name?:'Pemilik Folder'}}</strong><small class="d-block text-muted">Pemilik · akses penuh</small></div><span class="badge bg-label-success">Pemilik</span></div>@forelse($folder->permissions as $access)<div class="list-group-item p-3 d-flex align-items-center gap-3"><span class="avatar"><span class="avatar-initial rounded-circle bg-label-primary">{{strtoupper(substr($access->user?->name?:'U',0,1))}}</span></span><div class="flex-grow-1 min-w-0"><strong>{{$access->user?->name}}</strong><small class="d-block text-muted text-truncate">{{$access->user?->nip_nik?:$access->user?->username}} · {{$access->user?->role}}{{$access->user?->bidang?' · '.$access->user?->bidang:''}}</small><small class="text-muted">Dibagikan oleh {{$access->sharer?->name?:'Sistem'}} · {{$access->created_at->translatedFormat('d M Y H:i')}}</small></div><span class="badge bg-label-{{$access->permission==='contributor'?'primary':'secondary'}}">{{$access->permission==='contributor'?'Kontributor':'Pelihat'}}</span><form method="POST" action="{{route('documents.folder.sharing.destroy',[$folder,$access->user_id])}}" onsubmit="return confirm('Cabut akses {{$access->user?->name}} dari folder ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-icon btn-outline-danger"><i class="bx bx-x"></i></button></form></div>@empty<div class="text-center text-muted py-5"><i class="bx bx-user-plus fs-1"></i><p class="mt-2 mb-0">Folder belum dibagikan kepada pengguna lain.</p></div>@endforelse</div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{const input=document.getElementById('shareUserSearch'),results=document.getElementById('shareSearchResults'),hidden=document.getElementById('shareUserId'),selected=document.getElementById('selectedUser'),submit=document.getElementById('shareSubmit');let timer;input.addEventListener('input',()=>{clearTimeout(timer);hidden.value='';submit.disabled=true;selected.classList.add('d-none');if(input.value.trim().length<2){results.classList.add('d-none');return}timer=setTimeout(async()=>{const response=await fetch(@json(route('documents.share-users.search'))+'?q='+encodeURIComponent(input.value.trim()),{headers:{'Accept':'application/json'}});const users=await response.json();results.innerHTML=users.length?users.map(user=>`<button type="button" class="list-group-item list-group-item-action" data-id="${user.id}" data-name="${user.name}"><strong>${user.name}</strong><small class="d-block text-muted">${user.nip_nik||user.username||'-'} · ${user.role}${user.bidang?' · '+user.bidang:''}</small></button>`).join(''):'<div class="list-group-item text-muted">Pengguna tidak ditemukan.</div>';results.classList.remove('d-none');results.querySelectorAll('button').forEach(button=>button.onclick=()=>{hidden.value=button.dataset.id;selected.textContent='Dipilih: '+button.dataset.name;selected.classList.remove('d-none');submit.disabled=false;results.classList.add('d-none');input.value=button.dataset.name})},300)})});
</script>
<style>
.share-user-results{z-index:1080;max-height:280px;overflow-y:auto;top:calc(100% + 6px);left:0;background:#fff;border:1px solid #d9dee8;border-radius:.6rem;padding:.3rem;isolation:isolate}
.share-user-results .list-group-item{background:#fff!important;color:#566a7f!important;border:0;border-radius:.4rem;padding:.75rem .85rem;text-align:left}
.share-user-results .list-group-item+ .list-group-item{margin-top:.15rem}
.share-user-results .list-group-item strong{display:block;color:#384551!important}
.share-user-results .list-group-item small{color:#8592a3!important}
.share-user-results .list-group-item-action:hover,.share-user-results .list-group-item-action:focus{background:#f0f2ff!important;color:#696cff!important}
.share-user-results .list-group-item-action:hover strong,.share-user-results .list-group-item-action:focus strong{color:#696cff!important}
</style>
@endsection