@extends('layouts.master')
@section('title','Akun Penandatangan')
@section('content')
<div class="container-xxl container-p-y">
 <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
  <div><a href="{{ route('electronic-signatures.index') }}" class="small"><i class="bx bx-arrow-back"></i> Tanda Tangan Elektronik</a><h4 class="fw-bold mt-2 mb-1">Akun Penandatangan</h4><p class="text-muted mb-0">Identitas NIK/NIP pada akun digunakan sebagai identitas penandatangan di BSrE.</p></div>
  <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addSigner"><i class="bx bx-user-plus me-1"></i>Tambah Penandatangan</button>
 </div>
 @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
 @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
 @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
 <div class="alert alert-info border-0"><i class="bx bx-info-circle me-1"></i>Penandatangan login menggunakan <strong>NIK/NIP sebagai username</strong>. Ketika mendapat giliran, cukup membuka dokumen dan memasukkan passphrase BSrE.</div>
 <div class="card border-0 shadow-sm">
  <div class="card-header"><form class="d-flex gap-2"><div class="input-group"><span class="input-group-text"><i class="bx bx-search"></i></span><input name="q" value="{{ $search }}" class="form-control" placeholder="Cari nama, NIK/NIP, atau jabatan"></div><button class="btn btn-outline-primary">Cari</button>@if($search)<a href="{{ route('electronic-signatures.accounts') }}" class="btn btn-outline-secondary">Reset</a>@endif</form></div>
  <div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Penandatangan</th><th>NIK/NIP Login</th><th>Jabatan</th><th>Riwayat</th><th class="text-end">Aksi</th></tr></thead><tbody>
   @forelse($accounts as $account)<tr><td><strong>{{ $account->name }}</strong>@if($account->whatsapp)<small class="d-block text-muted">{{ $account->whatsapp }}</small>@endif</td><td><code>{{ $account->nip_nik }}</code></td><td>{{ $account->jabatan ?: '-' }}</td><td>{{ $account->electronic_signature_actors_count }} alur</td><td class="text-end"><button class="btn btn-sm btn-outline-warning" data-bs-toggle="modal" data-bs-target="#password{{ $account->id }}"><i class="bx bx-key"></i></button><form method="POST" action="{{ route('electronic-signatures.accounts.destroy',$account) }}" class="d-inline" onsubmit="return confirm('Hapus akun penandatangan ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" @disabled($account->electronic_signature_actors_count) title="{{ $account->electronic_signature_actors_count ? 'Tidak dapat dihapus karena memiliki riwayat' : 'Hapus akun' }}"><i class="bx bx-trash"></i></button></form></td></tr>
   @empty<tr><td colspan="5" class="text-center text-muted py-5">Belum ada akun penandatangan.</td></tr>@endforelse
  </tbody></table></div>@if($accounts->hasPages())<div class="card-footer">{{ $accounts->links() }}</div>@endif
 </div>
</div>
<div class="modal fade" id="addSigner" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form method="POST" action="{{ route('electronic-signatures.accounts.store') }}" class="modal-content">@csrf<div class="modal-header"><h5 class="modal-title">Tambah Akun Penandatangan</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Nama lengkap *</label><input name="name" value="{{ old('name') }}" class="form-control" required></div><div class="mb-3"><label class="form-label">NIK/NIP *</label><input name="nip_nik" value="{{ old('nip_nik') }}" class="form-control" inputmode="numeric" required><small class="text-muted">Otomatis menjadi username login dan identitas BSrE.</small></div><div class="row"><div class="col-md-6 mb-3"><label class="form-label">Jabatan</label><input name="jabatan" value="{{ old('jabatan') }}" class="form-control"></div><div class="col-md-6 mb-3"><label class="form-label">Nomor WhatsApp</label><input name="whatsapp" value="{{ old('whatsapp') }}" class="form-control"></div></div><div class="row"><div class="col-md-6"><label class="form-label">Password login *</label><input type="password" name="password" class="form-control" minlength="8" required></div><div class="col-md-6"><label class="form-label">Konfirmasi password *</label><input type="password" name="password_confirmation" class="form-control" minlength="8" required></div></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Akun</button></div></form></div></div>
@foreach($accounts as $account)<div class="modal fade" id="password{{ $account->id }}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form method="POST" action="{{ route('electronic-signatures.accounts.password',$account) }}" class="modal-content">@csrf @method('PUT')<div class="modal-header"><h5 class="modal-title">Ubah Password Login</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p class="text-muted">{{ $account->name }} · {{ $account->nip_nik }}</p><div class="mb-3"><label class="form-label">Password baru *</label><input type="password" name="password" minlength="8" class="form-control" required></div><div><label class="form-label">Konfirmasi password *</label><input type="password" name="password_confirmation" minlength="8" class="form-control" required></div></div><div class="modal-footer"><button class="btn btn-warning">Perbarui Password</button></div></form></div></div>@endforeach
@endsection
