@extends('layouts.master')
@section('title','Tanda Tangan Elektronik')
@section('content')
@php
$sources=[
 'training_certificates'=>['route'=>'electronic-signatures.integral','create'=>'electronic-signatures.integral.create','title'=>'Sertifikat Pelatihan Integral','short'=>'Integral','description'=>'Sertifikat peserta yang dibuat dari modul pelatihan Integral.','help'=>'Pilih pelatihan, sistem mengambil seluruh PDF hasil generate dan mengirim hasil final ke akun peserta.','icon'=>'bx-medal','color'=>'primary'],
 'jct_certificates'=>['route'=>'electronic-signatures.jct','create'=>'electronic-signatures.jct.create','title'=>'Sertifikat Jabar Corpu Talent','short'=>'JCT','description'=>'Sertifikat kegiatan yang bersumber dari Jabar Corpu Talent.','help'=>'Kegiatan dan peserta berasal dari JCT; hasil final dikirim kembali ke JCT.','icon'=>'bx-cloud','color'=>'info'],
 'other_documents'=>['route'=>'electronic-signatures.documents','create'=>'electronic-signatures.documents.create','title'=>'TTE Dokumen Lain','short'=>'Dokumen Lain','description'=>'Surat atau dokumen PDF di luar sertifikat pelatihan.','help'=>'Tulis nama kegiatan lalu unggah beberapa PDF atau satu bundel ZIP.','icon'=>'bx-file','color'=>'warning'],
];
$active=request('source');$meta=$active?($sources[$active]??null):null;$currentStats=$active?($documentStats[$active]??null):null;
@endphp
<div class="container-xxl container-p-y">
 <div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4"><div>@if($meta)<a href="{{route('electronic-signatures.index')}}" class="small"><i class="bx bx-arrow-back"></i> Pusat TTE</a>@endif<h4 class="fw-bold mt-2 mb-1">{{$meta?$meta['title']:'Pusat Tanda Tangan Elektronik'}}</h4><p class="text-muted mb-0">{{$meta?$meta['help']:'Pilih layanan sesuai asal dokumen agar prosesnya mudah dipantau.'}}</p></div><div class="d-flex gap-2 align-items-start">@if(Auth::user()->role==='superadmin')<a href="{{route('electronic-signatures.accounts')}}" class="btn btn-outline-primary"><i class="bx bx-user-check me-1"></i>Akun Penandatangan</a>@endif @if($meta&&request('source')!=='training_certificates'&&in_array(Auth::user()->role,['superadmin','admin_bidang'],true))<a href="{{route($meta['create'])}}" class="btn btn-{{$meta['color']}}"><i class="bx bx-plus me-1"></i>Buat Pengajuan {{$meta['short']}}</a>@endif</div></div>
 @if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
 @if(!$meta)
 <div class="row g-4 mb-4">@foreach($sources as $key=>$source)@php($stats=$documentStats[$key]??null)<div class="col-lg-4"><a href="{{route($source['route'])}}" class="card border-0 shadow-sm h-100 text-decoration-none service-card"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-start mb-4"><span class="avatar-initial rounded bg-label-{{$source['color']}} p-3"><i class="bx {{$source['icon']}} fs-2"></i></span><i class="bx bx-right-arrow-alt fs-3 text-{{$source['color']}}"></i></div><h5 class="text-dark fw-bold">{{$source['title']}}</h5><p class="text-muted">{{$source['description']}}</p><div class="d-flex gap-2"><span class="badge bg-label-secondary">{{$stats->total??0}} berkas</span><span class="badge bg-label-success">{{$stats->signed??0}} selesai</span></div></div></a></div>@endforeach</div>
 @php($chartMax=max(1,(int)$certificateChart->max('total')))
 <div class="card border-0 shadow-sm mb-4"><div class="card-header border-bottom d-flex flex-wrap justify-content-between align-items-center gap-2"><div><h5 class="fw-bold mb-1">Dokumen Ditandatangani Tahun {{$certificateYear}}</h5><small class="text-muted">Rekap Sertifikat Integral, Sertifikat JCT, dan Dokumen Lain yang selesai TTE setiap bulan.</small></div><div class="text-end"><h3 class="text-success mb-0">{{$certificateChart->sum('total')}}</h3><small class="text-muted">dokumen selesai TTE</small></div></div><div class="card-body"><div class="tte-chart">@foreach($certificateChart as $point)<div class="tte-chart__month"><div class="tte-chart__value">{{$point['total']?:''}}</div><div class="tte-chart__bars"><span class="tte-chart__bar bg-primary" style="height:{{round($point['integral']/$chartMax*150)}}px" title="Integral: {{$point['integral']}}"></span><span class="tte-chart__bar bg-info" style="height:{{round($point['jct']/$chartMax*150)}}px" title="JCT: {{$point['jct']}}"></span><span class="tte-chart__bar bg-warning" style="height:{{round($point['other']/$chartMax*150)}}px" title="Dokumen Lain: {{$point['other']}}"></span></div><small>{{$point['month']}}</small></div>@endforeach</div><div class="d-flex justify-content-center gap-4 small mt-3"><span><i class="d-inline-block rounded bg-primary me-1" style="width:10px;height:10px"></i>Integral</span><span><i class="d-inline-block rounded bg-info me-1" style="width:10px;height:10px"></i>JCT</span><span><i class="d-inline-block rounded bg-warning me-1" style="width:10px;height:10px"></i>Dokumen Lain</span></div></div></div>
 <div class="alert alert-info border-0"><i class="bx bx-info-circle me-1"></i>Penandatangan tidak membuat pengajuan. Setelah login, akun penandatangan cukup membuka bundel yang menjadi gilirannya dan memilih <strong>Tandatangani Semua</strong>.</div>
 @else
 <div class="row g-3 mb-4"><div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Total berkas</small><h3 class="mb-0">{{$currentStats->total??0}}</h3></div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Sudah ditandatangani</small><h3 class="text-success mb-0">{{$currentStats->signed??0}}</h3></div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Belum selesai</small><h3 class="text-warning mb-0">{{($currentStats->total??0)-($currentStats->signed??0)}}</h3></div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Giliran saya</small><h3 class="text-danger mb-0">{{$myPending}}</h3></div></div></div></div>
 <div class="card border-0 shadow-sm"><div class="card-header border-bottom"><form class="row g-2"><div class="col-md-7"><div class="input-group"><span class="input-group-text"><i class="bx bx-search"></i></span><input name="q" value="{{request('q')}}" class="form-control" placeholder="Cari nama kegiatan atau dokumen"></div></div><div class="col-md-3"><select name="status" class="form-select"><option value="">Semua status</option><option value="in_progress" @selected(request('status')==='in_progress')>Dalam proses</option><option value="completed" @selected(request('status')==='completed')>Selesai</option></select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Terapkan</button></div></form></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Bundel/Kegiatan</th><th>Bidang</th><th>Progres</th><th>Status</th><th></th></tr></thead><tbody>@forelse($requests as $item)@php($done=$item->completed_documents_count)<tr><td><strong>{{$item->title}}</strong><small class="d-block text-muted">Diajukan {{$item->creator?->name}} &middot; {{$item->created_at->translatedFormat('d M Y H:i')}}</small></td><td>{{$item->bidang?:'-'}}</td><td><strong>{{$done}}/{{$item->documents_count}}</strong><div class="progress mt-1" style="width:120px;height:6px"><div class="progress-bar bg-success" style="width:{{$item->documents_count?round($done/$item->documents_count*100):0}}%"></div></div></td><td><span class="badge bg-label-{{$item->status==='completed'?'success':'warning'}}">{{$item->status==='completed'?'Selesai':'Dalam proses'}}</span></td><td class="text-end"><div class="d-inline-flex gap-1"><a href="{{route('electronic-signatures.show',$item)}}" class="btn btn-sm btn-primary">Buka Bundel</a>@if(Auth::user()->role === 'superadmin' || (Auth::user()->role === 'admin_bidang' && Auth::user()->bidang === $item->bidang))<form method="POST" action="{{route('electronic-signatures.destroy',$item)}}" onsubmit="return confirm('Hapus seluruh pengajuan ini beserta semua berkasnya? Pengajuan yang sudah selesai TTE juga akan dihapus dan tindakan ini tidak dapat dibatalkan.')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" title="Hapus pengajuan"><i class="bx bx-trash"></i></button></form>@endif</div></td></tr>@empty<tr><td colspan="5" class="text-center py-5"><i class="bx bx-folder-open fs-1 text-muted"></i><p class="text-muted mt-2 mb-0">Belum ada pengajuan pada kategori ini.</p></td></tr>@endforelse</tbody></table></div>@if($requests->hasPages())<div class="card-footer">{{$requests->links()}}</div>@endif</div>
 @endif
</div>
<style>.service-card{transition:.2s ease}.service-card:hover{transform:translateY(-4px);box-shadow:0 .5rem 1.5rem rgba(67,89,113,.16)!important}.tte-chart{display:grid;grid-template-columns:repeat(12,minmax(42px,1fr));align-items:end;gap:.65rem;min-height:205px;padding:1rem .5rem 0;border-bottom:1px solid #e6e7eb;overflow-x:auto}.tte-chart__month{min-width:42px;text-align:center}.tte-chart__value{height:24px;font-size:.72rem;font-weight:700;color:#566a7f}.tte-chart__bars{height:150px;display:flex;align-items:flex-end;justify-content:center;gap:3px}.tte-chart__bar{display:block;width:12px;min-height:2px;border-radius:5px 5px 0 0;transition:.2s}.tte-chart__bar:hover{opacity:.75}.tte-chart__month small{display:block;padding:.55rem 0;color:#8592a3;font-weight:600}</style>
@endsection

