@extends('layouts.master')
@section('title','Akun Pengelola Magang')
@push('css')
<style>.manager-hero{border:0;border-radius:18px;background:linear-gradient(125deg,#214e67,#3b82a0,#4f9db9);color:#fff}.manager-card{border:0;border-radius:16px;box-shadow:0 6px 22px rgba(34,48,62,.08)}.manager-avatar{width:42px;height:42px;border-radius:12px;display:grid;place-items:center;background:#e9f5f8;color:#24738d;font-weight:700}</style>
@endpush
@section('content')
<div class="card manager-hero mb-4"><div class="card-body p-4 d-flex flex-column flex-lg-row justify-content-between gap-3"><div><a href="{{route('internships.index')}}" class="text-white opacity-75 small"><i class="bx bx-left-arrow-alt"></i> Presensi Magang/PKL</a><h3 class="text-white fw-bold mt-2 mb-1">Akun Pengelola Magang</h3><p class="mb-0 opacity-75">Buat akun operasional dengan akses terbatas pada program yang ditugaskan.</p></div><button class="btn btn-light text-primary align-self-lg-center" data-bs-toggle="modal" data-bs-target="#createManager"><i class="bx bx-user-plus me-1"></i>Tambah Pengelola</button></div></div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<div class="card manager-card"><div class="card-header border-bottom"><form class="row g-2"><div class="col"><div class="input-group"><span class="input-group-text"><i class="bx bx-search"></i></span><input name="q" value="{{$search}}" class="form-control" placeholder="Cari nama, username, atau WhatsApp"></div></div><div class="col-auto"><button class="btn btn-primary">Cari</button></div></form></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Pengelola</th><th>Username</th><th>WhatsApp</th><th>Program Ditugaskan</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($accounts as $account)<tr><td><div class="d-flex align-items-center gap-2"><span class="manager-avatar">{{mb_strtoupper(mb_substr($account->name,0,1))}}</span><strong>{{$account->name}}</strong></div></td><td><code>{{$account->username}}</code></td><td>{{$account->whatsapp}}</td><td><span class="badge bg-label-info">{{$account->managed_internship_programs_count}} program</span></td><td class="text-end"><button class="btn btn-sm btn-outline-warning" data-bs-toggle="modal" data-bs-target="#password{{$account->id}}" title="Reset password"><i class="bx bx-key"></i></button><form class="d-inline" method="POST" action="{{route('internships.managers.destroy',$account)}}" onsubmit="return confirm('Hapus akun pengelola ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" @disabled($account->managed_internship_programs_count) title="{{$account->managed_internship_programs_count?'Lepaskan penugasan program sebelum menghapus akun':'Hapus akun'}}"><i class="bx bx-trash"></i></button></form></td></tr><div class="modal fade" id="password{{$account->id}}"><div class="modal-dialog modal-dialog-centered"><form method="POST" action="{{route('internships.managers.password',$account)}}" class="modal-content">@csrf @method('PUT')<div class="modal-header"><h5 class="modal-title">Ubah Password {{$account->name}}</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Password baru</label><input type="password" name="password" class="form-control mb-3" minlength="8" required><label class="form-label">Konfirmasi password</label><input type="password" name="password_confirmation" class="form-control" minlength="8" required></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button class="btn btn-warning">Simpan Password</button></div></form></div></div>@empty<tr><td colspan="5" class="text-center py-5 text-muted"><i class="bx bx-user-x fs-1"></i><p class="mt-2 mb-0">Belum ada akun pengelola magang.</p></td></tr>@endforelse</tbody></table></div>@if($accounts->hasPages())<div class="card-footer">{{$accounts->links()}}</div>@endif</div>
<div class="modal fade" id="createManager"><div class="modal-dialog modal-dialog-centered"><form method="POST" action="{{route('internships.managers.store')}}" class="modal-content">@csrf<div class="modal-header"><div><h5 class="modal-title">Tambah Pengelola Magang</h5><small class="text-muted">Akun hanya memperoleh menu Presensi Magang/PKL.</small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-12"><label class="form-label">Nama lengkap *</label><input name="name" value="{{old('name')}}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Username *</label><input name="username" value="{{old('username')}}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Nomor WhatsApp *</label><input name="whatsapp" value="{{old('whatsapp')}}" class="form-control" inputmode="numeric" required></div><div class="col-md-6"><label class="form-label">Password *</label><input type="password" name="password" class="form-control" minlength="8" required></div><div class="col-md-6"><label class="form-label">Konfirmasi password *</label><input type="password" name="password_confirmation" class="form-control" minlength="8" required></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Buat Akun</button></div></form></div></div>
@endsection