@extends('layouts.master')
@section('title','Presensi Magang/PKL')
@section('content')
<style>.intern-hero{border:0;border-radius:20px;background:linear-gradient(125deg,#214e67,#3b82a0,#4f9db9);color:#fff}.program-card{border:0;border-radius:16px;box-shadow:0 5px 22px rgba(34,48,62,.07);transition:.2s}.program-card:hover{transform:translateY(-2px);box-shadow:0 10px 28px rgba(34,48,62,.11)}</style>
<div class="card intern-hero mb-4"><div class="card-body p-4 d-flex flex-column flex-lg-row justify-content-between gap-3"><div><span class="badge bg-white text-primary mb-2">Modul Mandiri</span><h3 class="text-white fw-bold mb-1">Presensi Magang/PKL</h3><p class="mb-0 opacity-75">Kelola periode, pendaftaran, akun, dan aktivitas peserta magang.</p></div><button class="btn btn-light align-self-lg-center" data-bs-toggle="modal" data-bs-target="#createProgram"><i class="bx bx-plus me-1"></i>Buat Program</button></div></div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><form class="row g-2"><div class="col-md-10"><input name="q" value="{{request('q')}}" class="form-control" placeholder="Cari program magang..."></div><div class="col-md-2 d-grid"><button class="btn btn-primary"><i class="bx bx-search me-1"></i>Cari</button></div></form></div></div>
<div class="row g-4">@forelse($programs as $program)<div class="col-md-6 col-xl-4"><div class="card program-card h-100"><div class="card-body"><div class="d-flex justify-content-between mb-3"><span class="badge bg-label-{{$program->status==='open'?'success':'secondary'}}">{{ucfirst($program->status)}}</span>@if($program->pending_count)<span class="badge bg-danger rounded-pill">{{$program->pending_count}} menunggu</span>@endif</div><h5 class="fw-bold">{{$program->title}}</h5><p class="small text-muted mb-3"><i class="bx bx-building me-1"></i>{{$program->bidang?:'Lintas bidang'}}</p><div class="d-flex gap-2 mb-3"><div class="bg-label-primary rounded p-2 flex-fill text-center"><strong>{{$program->participants_count}}</strong><small class="d-block">Peserta</small></div><div class="bg-label-warning rounded p-2 flex-fill text-center"><strong>{{$program->pending_count}}</strong><small class="d-block">Pending</small></div></div><a href="{{route('internships.show',$program)}}" class="btn btn-primary w-100">Kelola Program <i class="bx bx-right-arrow-alt ms-1"></i></a></div></div></div>@empty<div class="col-12"><div class="card border-0"><div class="card-body text-center py-5 text-muted"><i class="bx bx-briefcase-alt-2 fs-1"></i><h6 class="mt-2">Belum ada program magang</h6></div></div></div>@endforelse</div><div class="mt-4">{{$programs->links()}}</div>
<div class="modal fade" id="createProgram"><div class="modal-dialog modal-lg modal-dialog-centered"><form method="POST" action="{{route('internships.store')}}" class="modal-content">@csrf<div class="modal-header"><div><h5 class="modal-title fw-bold">Program Magang Baru</h5><small class="text-muted">Jam presensi dapat disesuaikan kembali.</small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-12"><label class="form-label">Nama program *</label><input name="title" class="form-control" required></div>@if(Auth::user()->role==='superadmin')<div class="col-12"><label class="form-label">Bidang pengelola</label><input name="bidang" class="form-control"></div>@endif<div class="col-12"><label class="form-label">Deskripsi</label><textarea name="description" class="form-control" rows="3"></textarea></div><div class="col-md-6"><label class="form-label">Pendaftaran dibuka</label><input type="date" name="registration_opens_at" class="form-control"></div><div class="col-md-6"><label class="form-label">Pendaftaran ditutup</label><input type="date" name="registration_closes_at" class="form-control"></div><div class="col-md-4"><label class="form-label">Mulai absen</label><input type="time" name="check_in_opens_at" value="06:00" class="form-control" required></div><div class="col-md-4"><label class="form-label">Batas terlambat</label><input type="time" name="late_after" value="07:30" class="form-control" required></div><div class="col-md-4"><label class="form-label">Mulai pulang</label><input type="time" name="check_out_opens_at" value="16:00" class="form-control" required></div><div class="col-12"><label class="form-label">Status</label><select name="status" class="form-select"><option value="draft">Draft</option><option value="open">Buka pendaftaran</option></select></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan Program</button></div></form></div></div>
@endsection