@extends('layouts.master')
@section('title','Dashboard Magang')
@section('content')
<style>
.intern-welcome{border:0;border-radius:22px;background:linear-gradient(125deg,#183f54,#2e7894 60%,#4f9db9);color:#fff;overflow:hidden}.intern-welcome h2{color:#fff!important}.welcome-kicker{background:#fff!important;color:#235f77!important;border:0!important;padding:8px 13px!important}.welcome-meta{display:inline-flex;align-items:center;background:rgba(255,255,255,.14)!important;border:1px solid rgba(255,255,255,.22)!important;color:#fff!important;border-radius:30px!important;padding:8px 12px!important;white-space:normal}
.stat-card,.attendance-card{border:0;border-radius:17px;box-shadow:0 5px 22px rgba(34,48,62,.07);background:#fff!important;color:#344054!important}.attendance-card .card-header{background:#fff!important;color:#344054!important}.stat-card h4,.attendance-card h5,.attendance-card h6{color:#344054!important}
.bell-action{width:88px;height:88px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;font-size:42px;border:0;transition:.2s}.bell-action.active{background:#56c51f!important;color:#fff!important;box-shadow:0 10px 25px rgba(86,197,31,.3);animation:pulseBell 2s infinite}.bell-action.disabled{background:#e7e9ee!important;color:#7c8592!important}.bell-action i{color:inherit!important}
.camera-modal .modal-content{background:#fff!important;color:#344054!important;border:0;border-radius:20px;overflow:hidden}.camera-modal .modal-header,.camera-modal .modal-footer{background:#fff!important}.camera-stage{position:relative;background:#111827;border-radius:16px;overflow:hidden;min-height:280px;display:flex;align-items:center;justify-content:center}.camera-video,.camera-preview{width:100%;max-height:420px;object-fit:cover}.camera-preview{display:none}.camera-placeholder{color:#cbd5e1;text-align:center;padding:40px}.camera-status{border-radius:12px}.btn-camera{background:#27708e!important;border-color:#27708e!important;color:#fff!important}.btn-camera:hover{background:#1e5a72!important;color:#fff!important}.fallback-upload{color:#27708e!important;background:#fff!important;border:1px solid #80b4c8!important}
@keyframes pulseBell{50%{transform:scale(1.05)}}.timeline-dot{width:12px;height:12px;border-radius:50%;background:#696cff;flex:0 0 auto;margin-top:5px}
@media(max-width:575.98px){.welcome-meta{width:100%;border-radius:12px!important}.bell-action{width:78px;height:78px}.camera-stage{min-height:240px}}
</style>
<div class="card intern-welcome mb-4"><div class="card-body p-4 p-lg-5"><span class="badge welcome-kicker mb-3">Peserta Magang/PKL</span><h2 class="text-white fw-bold mb-1">Selamat datang, {{$participant->name}}</h2><p class="mb-3 opacity-75">{{$participant->institution}} &middot; {{$participant->major}}</p><div class="d-flex flex-wrap gap-2"><span class="badge welcome-meta"><i class="bx bx-building me-1"></i>{{$participant->placement_unit}}</span><span class="badge welcome-meta"><i class="bx bx-calendar me-1"></i>{{$participant->start_date->translatedFormat('d M Y')}} s.d. {{$participant->end_date->translatedFormat('d M Y')}}</span></div></div></div>
@if(session('success'))<div class="alert alert-success"><i class="bx bx-check-circle me-1"></i>{{session('success')}}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Presensi belum berhasil:</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $e)<li>{{$e}}</li>@endforeach</ul></div>@endif
<div class="row g-3 mb-4">@foreach([['Total Kehadiran',$stats['present'],'bx-check-circle','success'],['Hari Terlambat',$stats['late_days'],'bx-time-five','warning'],['Akumulasi Terlambat',$stats['late_minutes'].' menit','bx-timer','danger'],['Izin / Sakit',($stats['permission']+$stats['sick']),'bx-file','info']] as $s)<div class="col-6 col-xl-3"><div class="card stat-card h-100"><div class="card-body"><i class="bx {{$s[2]}} text-{{$s[3]}} fs-2"></i><h4 class="fw-bold mt-2 mb-0">{{$s[1]}}</h4><small class="text-muted">{{$s[0]}}</small></div></div></div>@endforeach</div>
@if($internshipEnded)
<div class="card attendance-card overflow-hidden">
 <div class="card-body p-4 p-lg-5 text-center">
  <span class="d-inline-flex align-items-center justify-content-center rounded-circle bg-label-success mb-3" style="width:88px;height:88px"><i class="bx bx-award text-success" style="font-size:48px"></i></span>
  <span class="badge bg-label-success d-block mx-auto mb-3" style="width:max-content">Masa Magang Selesai</span>
  <h3 class="fw-bold">Terima kasih, {{$participant->name}}</h3>
  <p class="text-muted mx-auto" style="max-width:620px">Periode magang Anda telah berakhir pada {{$participant->end_date->translatedFormat('d F Y')}}. Menu presensi sudah ditutup dan digantikan dengan layanan sertifikat.</p>
  @if($certificateAvailable)
   <div class="border rounded-3 p-3 mx-auto mb-3 text-start" style="max-width:520px"><small class="text-muted d-block">Nomor sertifikat</small><strong>{{$participant->certificate_number}}</strong><hr class="my-2"><small class="text-muted d-block">Predikat akhir</small><strong class="text-success">{{$participant->final_grade}}</strong></div>
   <a href="{{route('internships.certificate.download')}}" class="btn btn-success btn-lg"><i class="bx bx-download me-1"></i>Download Sertifikat PDF</a>
  @else
   <div class="alert alert-warning mx-auto mb-0" style="max-width:620px"><i class="bx bx-time-five me-1"></i>Sertifikat sedang disiapkan oleh pengelola. Tombol download akan muncul setelah sertifikat diterbitkan.</div>
  @endif
 </div>
</div>
@else
<div class="row g-4"><div class="col-lg-7"><div class="card attendance-card"><div class="card-header border-bottom"><div class="d-flex justify-content-between align-items-center"><div><h5 class="fw-bold mb-1">Presensi Hari Ini</h5><small class="text-muted">{{$now->translatedFormat('l, d F Y')}} &middot; {{$now->format('H:i')}} WIB</small></div>@if($todayAttendance)<span class="badge bg-label-{{$todayAttendance->status==='present'?'success':'warning'}}">{{ucfirst($todayAttendance->status)}}</span>@endif</div></div><div class="card-body p-4 text-center">
@if(!$todayAttendance)
<button class="bell-action {{$canCheckIn?'active':'disabled'}}" {{$canCheckIn?'data-bs-toggle=modal data-bs-target=#checkInModal':'disabled'}}><i class="bx bx-bell"></i></button><h5 class="fw-bold mt-3">{{$canCheckIn?'Presensi Masuk Tersedia':'Presensi Belum Dibuka'}}</h5><p class="text-muted">Mulai {{substr($participant->program->check_in_opens_at,0,5)}} WIB. Setelah {{substr($participant->program->late_after,0,5)}} WIB tercatat terlambat.</p><div class="d-flex justify-content-center gap-2"><button class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#absenceModal" data-type="permission"><i class="bx bx-time me-1"></i>Izin</button><button class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#absenceModal" data-type="sick"><i class="bx bx-plus-medical me-1"></i>Sakit</button></div>
@elseif($todayAttendance->status==='present')
<div class="row align-items-center"><div class="col-sm-6 mb-3"><i class="bx bx-check-circle text-success" style="font-size:64px"></i><h6 class="fw-bold">Masuk {{$todayAttendance->check_in_at?->format('H:i')}}</h6>@if($todayAttendance->late_minutes)<span class="badge bg-label-danger">Terlambat {{$todayAttendance->late_minutes}} menit</span>@else<span class="badge bg-label-success">Tepat waktu</span>@endif</div><div class="col-sm-6 mb-3"><button class="bell-action {{$canCheckOut?'active':'disabled'}}" {{$canCheckOut?'data-bs-toggle=modal data-bs-target=#checkOutModal':'disabled'}}><i class="bx bx-log-out-circle"></i></button><h6 class="fw-bold mt-2">{{$todayAttendance->check_out_at?'Pulang '.$todayAttendance->check_out_at->format('H:i'):($canCheckOut?'Presensi Pulang':'Pulang mulai '.$participant->program->check_out_opens_at)}}</h6></div></div>
@else<i class="bx {{$todayAttendance->status==='sick'?'bx-plus-medical text-danger':'bx-time-five text-warning'}}" style="font-size:64px"></i><h5 class="fw-bold mt-3">{{ $todayAttendance->status==='sick'?'Sakit':'Izin' }} Tercatat</h5><p class="text-muted mb-0">Kehadiran Anda tetap dihitung hadir secara administratif. Anda tidak perlu melakukan presensi masuk maupun pulang hari ini.</p>@endif
</div></div></div>
<div class="col-lg-5"><div class="card attendance-card h-100"><div class="card-header border-bottom"><h5 class="fw-bold mb-1">Riwayat Terakhir</h5><small class="text-muted">Foto otomatis dihapus setelah 7 hari.</small></div><div class="card-body">@forelse($attendances as $a)<div class="d-flex gap-3 mb-3"><span class="timeline-dot"></span><div class="flex-grow-1"><div class="d-flex justify-content-between"><strong>{{$a->attendance_date->translatedFormat('d M Y')}}</strong><span class="badge bg-label-{{$a->status==='present'?'success':'warning'}}">{{ucfirst($a->status)}}</span></div><small class="text-muted">@if($a->status==='present')Masuk {{$a->check_in_at?->format('H:i')}} � Pulang {{$a->check_out_at?->format('H:i')?:'-'}}@else Tercatat sebagai hadir administratif @endif</small></div></div>@empty<div class="text-center text-muted py-5">Belum ada riwayat.</div>@endforelse</div></div></div></div>
@endif
@foreach([['checkInModal','Presensi Masuk','internships.attendance.check-in'],['checkOutModal','Presensi Pulang','internships.attendance.check-out']] as $modal)
<div class="modal fade camera-modal" id="{{$modal[0]}}" tabindex="-1" data-bs-backdrop="static">
 <div class="modal-dialog modal-dialog-centered modal-lg">
  <form method="POST" action="{{route($modal[2])}}" enctype="multipart/form-data" class="modal-content selfie-form">@csrf
   <div class="modal-header"><div><h5 class="modal-title fw-bold">{{$modal[1]}}</h5><small class="text-muted">Ambil foto wajah secara langsung untuk mencatat kehadiran.</small></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
   <div class="modal-body p-4">
    <div class="alert alert-info camera-status small"><i class="bx bx-shield-quarter me-1"></i>Kamera memerlukan izin browser. Foto otomatis dihapus setelah 7 hari.</div>
    <div class="camera-stage mb-3"><video class="camera-video" autoplay playsinline muted></video><img class="camera-preview" alt="Hasil selfie"><div class="camera-placeholder"><i class="bx bx-camera fs-1 d-block mb-2"></i>Menyiapkan kamera...</div><canvas class="d-none camera-canvas"></canvas></div>
    <input type="file" name="selfie" accept="image/*" capture="user" class="d-none selfie-input" required>
    <div class="d-flex flex-wrap justify-content-center gap-2"><button type="button" class="btn btn-camera start-camera"><i class="bx bx-webcam me-1"></i>Aktifkan Kamera</button><button type="button" class="btn btn-success capture-camera" disabled><i class="bx bx-camera me-1"></i>Ambil Selfie</button><button type="button" class="btn btn-outline-secondary retake-camera d-none"><i class="bx bx-refresh me-1"></i>Foto Ulang</button><label class="btn fallback-upload mb-0"><i class="bx bx-image-add me-1"></i>Pilih Foto<input type="file" accept="image/*" capture="user" class="d-none fallback-input"></label></div>
    <small class="d-block text-center text-muted mt-3">Pastikan wajah terlihat jelas. Maksimal 5 MB.</small>
   </div>
   <div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary submit-selfie" disabled><i class="bx bx-send me-1"></i>Kirim {{$modal[1]}}</button></div>
  </form>
 </div>
</div>
@endforeach
<div class="modal fade" id="absenceModal"><div class="modal-dialog modal-dialog-centered"><form method="POST" action="{{route('internships.attendance.absence')}}" enctype="multipart/form-data" class="modal-content">@csrf<input type="hidden" name="type" id="absenceType"><div class="modal-header"><h5 class="modal-title fw-bold" id="absenceTitle">Pengajuan</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Keterangan jelas *</label><textarea name="note" minlength="10" rows="4" class="form-control" required></textarea></div><div id="evidenceBox"><label class="form-label">Bukti sakit *</label><input type="file" name="evidence" accept=".pdf,image/*" class="form-control"><small class="text-muted">PDF/JPG/PNG, maksimal 5 MB.</small></div></div><div class="modal-footer"><button class="btn btn-primary">Kirim Pengajuan</button></div></form></div></div>
@endsection
@push('js')
<script>
document.querySelectorAll('.camera-modal').forEach(modal=>{
 const video=modal.querySelector('.camera-video'),preview=modal.querySelector('.camera-preview'),canvas=modal.querySelector('.camera-canvas'),input=modal.querySelector('.selfie-input'),fallback=modal.querySelector('.fallback-input'),start=modal.querySelector('.start-camera'),capture=modal.querySelector('.capture-camera'),retake=modal.querySelector('.retake-camera'),submit=modal.querySelector('.submit-selfie'),placeholder=modal.querySelector('.camera-placeholder'),status=modal.querySelector('.camera-status');
 const stopCamera=()=>{if(modal._stream){modal._stream.getTracks().forEach(track=>track.stop());modal._stream=null}video.srcObject=null};
 const setPhoto=file=>{const transfer=new DataTransfer();transfer.items.add(file);input.files=transfer.files;preview.src=URL.createObjectURL(file);preview.style.display='block';video.style.display='none';placeholder.style.display='none';capture.classList.add('d-none');retake.classList.remove('d-none');submit.disabled=false;status.className='alert alert-success camera-status small';status.innerHTML='<i class="bx bx-check-circle me-1"></i>Selfie siap dikirim. Periksa foto sebelum melanjutkan.'};
 const startCamera=async()=>{stopCamera();preview.style.display='none';video.style.display='block';placeholder.style.display='block';placeholder.innerHTML='<i class="bx bx-loader-alt bx-spin fs-1 d-block mb-2"></i>Meminta izin kamera...';retake.classList.add('d-none');capture.classList.remove('d-none');capture.disabled=true;submit.disabled=true;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unsupported');modal._stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=modal._stream;await video.play();placeholder.style.display='none';capture.disabled=false;start.classList.add('d-none');status.className='alert alert-info camera-status small';status.innerHTML='<i class="bx bx-webcam me-1"></i>Kamera aktif. Posisikan wajah di tengah lalu pilih Ambil Selfie.'}catch(error){video.style.display='none';placeholder.style.display='block';placeholder.innerHTML='<i class="bx bx-error-circle fs-1 d-block mb-2"></i>Kamera tidak dapat dibuka.<small class="d-block mt-2">Izinkan kamera pada browser atau gunakan Pilih Foto.</small>';status.className='alert alert-warning camera-status small';status.innerHTML='<i class="bx bx-info-circle me-1"></i>Akses kamera memerlukan HTTPS atau localhost dan izin dari pengguna.'}};
 start.addEventListener('click',startCamera);retake.addEventListener('click',startCamera);
 capture.addEventListener('click',()=>{if(!video.videoWidth)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);canvas.toBlob(blob=>{if(!blob)return;setPhoto(new File([blob],'selfie-'+Date.now()+'.jpg',{type:'image/jpeg'}));stopCamera()},'image/jpeg',.88)});
 fallback.addEventListener('change',()=>{if(fallback.files[0]){setPhoto(fallback.files[0]);stopCamera()}});
 modal.addEventListener('shown.bs.modal',startCamera);modal.addEventListener('hidden.bs.modal',stopCamera);
});
document.getElementById('absenceModal')?.addEventListener('show.bs.modal',e=>{const type=e.relatedTarget.dataset.type,sick=type==='sick',box=document.getElementById('evidenceBox');document.getElementById('absenceType').value=type;document.getElementById('absenceTitle').textContent=sick?'Catat Sakit':'Catat Izin';box.style.display=sick?'block':'none';box.querySelector('input').required=sick;});
</script>
@endpush