@extends('layouts.master')
@section('title','Master Kepegawaian')
@section('content')
<div class="container-xxl container-p-y">
 <div class="p-4 rounded-4 text-white mb-4" style="background:linear-gradient(120deg,#253f85,#637ced)"><small>PENGATURAN SISTEM</small><h3 class="text-white fw-bold mb-1">Master Instansi & Status Kepegawaian</h3><p class="mb-0 text-white-50">Kelola pilihan profil tanpa mengubah source code.</p></div>
 @if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
 @if(session('error'))<div class="alert alert-danger">{{session('error')}}</div>@endif
 @if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif
 <div class="row g-4">
  <div class="col-xl-7"><div class="card border-0 shadow-sm"><div class="card-header d-flex flex-wrap justify-content-between gap-2"><div><h5 class="mb-0">Daftar Perangkat Daerah/Instansi</h5><small class="text-muted">Kode dibuat otomatis dari nama instansi.</small></div><div class="d-flex flex-wrap gap-1"><a href="{{route('workforce-masters.institutions.template')}}" class="btn btn-sm btn-outline-success"><i class="bx bx-download"></i> Template</a><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#importInstitutionModal"><i class="bx bx-upload"></i> Import</button><button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#institutionModal"><i class="bx bx-plus"></i> Tambah</button></div></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Instansi</th><th>Kode Otomatis</th><th>Status</th><th></th></tr></thead><tbody>
  @foreach($institutions as $item)<tr><td><strong>{{$item->name}}</strong>@if($item->is_internal_bpsdm)<span class="badge bg-label-success ms-1">Internal BPSDM</span>@endif</td><td><code>{{$item->code?:'-'}}</code></td><td><span class="badge bg-label-{{$item->is_active?'success':'secondary'}}">{{$item->is_active?'Aktif':'Nonaktif'}}</span></td><td><div class="d-flex gap-1"><button class="btn btn-sm btn-outline-primary edit-institution" data-bs-toggle="modal" data-bs-target="#editInstitutionModal" data-action="{{route('workforce-masters.institutions.update',$item)}}" data-name="{{$item->name}}" data-active="{{$item->is_active?1:0}}" data-internal="{{$item->is_internal_bpsdm?1:0}}" data-sort="{{$item->sort_order}}"><i class="bx bx-edit"></i></button><button class="btn btn-sm btn-outline-danger delete-master" data-bs-toggle="modal" data-bs-target="#deleteModal" data-action="{{route('workforce-masters.institutions.destroy',$item)}}" data-name="{{$item->name}}" data-type="instansi"><i class="bx bx-trash"></i></button></div></td></tr>@endforeach
  </tbody></table></div></div></div>
  <div class="col-xl-5"><div class="card border-0 shadow-sm"><div class="card-header d-flex justify-content-between"><div><h5 class="mb-0">Status Kepegawaian</h5><small class="text-muted">Pilihan aktif muncul di profil.</small></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#statusModal"><i class="bx bx-plus"></i></button></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Status</th><th>Aktif</th><th></th></tr></thead><tbody>
  @foreach($statuses as $item)<tr><td><strong>{{$item->name}}</strong><small class="d-block text-muted">{{$item->code}}</small></td><td><span class="badge bg-label-{{$item->is_active?'success':'secondary'}}">{{$item->is_active?'Ya':'Tidak'}}</span></td><td><div class="d-flex gap-1"><button class="btn btn-sm btn-outline-primary edit-status" data-bs-toggle="modal" data-bs-target="#editStatusModal" data-action="{{route('workforce-masters.statuses.update',$item)}}" data-name="{{$item->name}}" data-code="{{$item->code}}" data-description="{{$item->description}}" data-active="{{$item->is_active?1:0}}" data-sort="{{$item->sort_order}}"><i class="bx bx-edit"></i></button><button class="btn btn-sm btn-outline-danger delete-master" data-bs-toggle="modal" data-bs-target="#deleteModal" data-action="{{route('workforce-masters.statuses.destroy',$item)}}" data-name="{{$item->name}}" data-type="status"><i class="bx bx-trash"></i></button></div></td></tr>@endforeach
  </tbody></table></div></div></div>
 </div>
</div>
<div class="modal fade" id="institutionModal"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{route('workforce-masters.institutions.store')}}">@csrf<div class="modal-header"><h5>Tambah Instansi</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-8"><label>Nama resmi</label><input name="name" class="form-control" required><small class="text-muted">Kode dibuat otomatis oleh sistem.</small></div><div class="col-4"><label>Urutan</label><input name="sort_order" type="number" min="0" value="0" class="form-control"></div><div class="col-12 form-check ms-2"><input type="hidden" name="is_internal_bpsdm" value="0"><input class="form-check-input" type="checkbox" name="is_internal_bpsdm" value="1" id="internal"><label for="internal">Instansi internal BPSDM Jabar</label></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="importInstitutionModal"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" enctype="multipart/form-data" action="{{route('workforce-masters.institutions.import')}}">@csrf<div class="modal-header"><div><h5 class="mb-0">Import Perangkat Daerah</h5><small class="text-muted">Gunakan template resmi agar kolom dikenali.</small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-info"><strong>Kolom template:</strong><ul class="mb-0 mt-1"><li>Nama Perangkat Daerah</li><li>Urutan</li><li>Status Aktif: Ya/Tidak</li></ul></div><label class="form-label fw-bold">File Excel</label><input type="file" name="file" class="form-control" accept=".xlsx,.xls" required><small class="text-muted">Maksimal 10 MB. Data dengan nama sama akan diperbarui.</small></div><div class="modal-footer"><a href="{{route('workforce-masters.institutions.template')}}" class="btn btn-outline-success"><i class="bx bx-download"></i> Unduh Template</a><button class="btn btn-primary"><i class="bx bx-upload"></i> Import Data</button></div></form></div></div>
<div class="modal fade" id="statusModal"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{route('workforce-masters.statuses.store')}}">@csrf<div class="modal-header"><h5>Tambah Status</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-7"><label>Nama status</label><input name="name" class="form-control" required></div><div class="col-5"><label>Kode</label><input name="code" class="form-control" required></div><div class="col-12"><label>Keterangan</label><textarea name="description" class="form-control"></textarea></div><input type="hidden" name="sort_order" value="0"></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="editInstitutionModal"><div class="modal-dialog modal-dialog-centered"><form id="editInstitutionForm" class="modal-content" method="POST">@csrf @method('PUT')<div class="modal-header"><h5>Edit Instansi</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-8"><input name="name" id="eiName" class="form-control" required><small class="text-muted">Kode diperbarui otomatis mengikuti nama.</small></div><div class="col-4"><input name="sort_order" id="eiSort" type="number" class="form-control"></div><div class="col-6"><label>Status</label><select name="is_active" id="eiActive" class="form-select"><option value="1">Aktif</option><option value="0">Nonaktif</option></select></div><div class="col-6"><label>Internal</label><select name="is_internal_bpsdm" id="eiInternal" class="form-select"><option value="0">Tidak</option><option value="1">Ya</option></select></div></div><div class="modal-footer"><button class="btn btn-primary">Perbarui</button></div></form></div></div>
<div class="modal fade" id="editStatusModal"><div class="modal-dialog modal-dialog-centered"><form id="editStatusForm" class="modal-content" method="POST">@csrf @method('PUT')<div class="modal-header"><h5>Edit Status</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-7"><input name="name" id="esName" class="form-control" required></div><div class="col-5"><input name="code" id="esCode" class="form-control" required></div><div class="col-12"><textarea name="description" id="esDescription" class="form-control"></textarea></div><div class="col-6"><select name="is_active" id="esActive" class="form-select"><option value="1">Aktif</option><option value="0">Nonaktif</option></select></div><div class="col-6"><input name="sort_order" id="esSort" type="number" class="form-control"></div></div><div class="modal-footer"><button class="btn btn-primary">Perbarui</button></div></form></div></div>
<div class="modal fade" id="deleteModal"><div class="modal-dialog modal-dialog-centered"><form id="deleteForm" method="POST" class="modal-content">@csrf @method('DELETE')<div class="modal-body text-center p-5"><span class="d-inline-block rounded-circle bg-label-danger p-3"><i class="bx bx-trash fs-2"></i></span><h5 class="fw-bold mt-3">Hapus <span id="deleteType"></span>?</h5><p class="text-muted"><strong id="deleteName"></strong> akan dihapus. Data yang sudah digunakan harus dinonaktifkan agar riwayat tetap aman.</p><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button> <button class="btn btn-danger">Ya, Hapus</button></div></form></div></div>
@endsection
@push('js')<script>document.querySelectorAll('.edit-institution').forEach(b=>b.onclick=()=>{editInstitutionForm.action=b.dataset.action;eiName.value=b.dataset.name;eiSort.value=b.dataset.sort;eiActive.value=b.dataset.active;eiInternal.value=b.dataset.internal});document.querySelectorAll('.edit-status').forEach(b=>b.onclick=()=>{editStatusForm.action=b.dataset.action;esName.value=b.dataset.name;esCode.value=b.dataset.code;esDescription.value=b.dataset.description;esActive.value=b.dataset.active;esSort.value=b.dataset.sort});document.querySelectorAll('.delete-master').forEach(b=>b.onclick=()=>{deleteForm.action=b.dataset.action;deleteName.textContent=b.dataset.name;deleteType.textContent=b.dataset.type});</script>@endpush
