@extends('layouts.master')
@section('title','Manajemen Mutu')
@section('content')
<div class="container-xxl container-p-y">
 <div class="qm-hero mb-4"><div><span class="eyebrow"><i class="bx bx-check-shield"></i> KENDALI KELENGKAPAN</span><h3 class="text-white fw-bold mt-2 mb-1">Manajemen Mutu Pelatihan</h3><p class="mb-0 text-white-50">Pantau kesiapan 42 dokumen pada setiap pelatihan dalam satu tampilan.</p></div><div class="hero-icon"><i class="bx bx-folder-open"></i></div></div>
 @if(session('success'))<div class="alert alert-success"><i class="bx bx-check-circle me-1"></i>{{session('success')}}</div>@endif
 <div class="card border-0 shadow-sm mb-4"><div class="card-body"><form class="row g-2 align-items-end"><div class="col-lg-6"><label class="form-label">Cari pelatihan</label><div class="input-group"><span class="input-group-text"><i class="bx bx-search"></i></span><input name="search" value="{{request('search')}}" class="form-control" placeholder="Ketik nama pelatihan..."></div></div><div class="col-lg-4"><label class="form-label">Bidang penyelenggara</label><select name="bidang" class="form-select" @disabled(auth()->user()->role==='admin_bidang')><option value="">Semua bidang</option>@foreach($bidangs as $bidang)<option value="{{$bidang}}" @selected(request('bidang')===$bidang)>{{$bidang}}</option>@endforeach</select></div><div class="col-lg-2 d-flex gap-2"><button class="btn btn-primary flex-grow-1">Terapkan</button><a href="{{route('quality-management.index')}}" class="btn btn-outline-secondary"><i class="bx bx-reset"></i></a></div></form></div></div>
 <div class="row g-3">@forelse($trainings as $training)
 @php
     $requiredTotal = max(0, $totalRequirements - $training->quality_not_required_count);
     $percent = $requiredTotal ? round($training->quality_completed_count / $requiredTotal * 100) : 100;
 @endphp
 <div class="col-md-6 col-xl-4"><div class="card training-card h-100 border-0 shadow-sm"><div class="card-body"><div class="d-flex justify-content-between gap-3 mb-3"><span class="badge bg-label-primary text-wrap text-start">{{$training->bidang ?: 'Bidang belum ditentukan'}}</span><span class="date"><i class="bx bx-calendar"></i> {{optional($training->tgl_mulai ? \Carbon\Carbon::parse($training->tgl_mulai):null)->format('d M Y') ?: '-'}}</span></div><h5 class="fw-bold training-title">{{$training->nama_pelatihan}}</h5><div class="d-flex justify-content-between mt-4 mb-2"><strong>{{$training->quality_completed_count}} / {{$requiredTotal}} dokumen wajib</strong><span class="fw-bold text-primary">{{$percent}}%</span></div><div class="progress"><div class="progress-bar" style="width:{{$percent}}%"></div></div><small class="text-muted d-block mt-2">{{$training->quality_not_required_count}} dokumen Tidak Berlaku</small></div><div class="card-footer bg-transparent border-top d-flex justify-content-between align-items-center"><small class="text-muted">{{ $percent===100 ? 'Kelengkapan wajib selesai' : ($requiredTotal-$training->quality_completed_count).' dokumen wajib belum tersedia' }}</small><a href="{{route('quality-management.show',$training)}}" class="btn btn-sm btn-primary">Kelola Dokumen <i class="bx bx-right-arrow-alt"></i></a></div></div></div>
 @empty <div class="col-12"><div class="card border-0 shadow-sm"><div class="card-body text-center py-5"><i class="bx bx-folder-open display-3 text-muted"></i><h5 class="mt-3">Pelatihan tidak ditemukan</h5><p class="text-muted mb-0">Coba ubah kata pencarian atau filter bidang.</p></div></div></div>@endforelse</div>
 @if($trainings->hasPages())<div class="mt-4">{{$trainings->links()}}</div>@endif
</div>
@endsection
@push('css')<style>.qm-hero{background:linear-gradient(125deg,#224a9b,#587ee8);padding:2rem;border-radius:20px;display:flex;align-items:center;justify-content:space-between;box-shadow:0 16px 35px rgba(34,74,155,.2)}.eyebrow{font-size:.72rem;letter-spacing:.12em;color:#dce8ff}.hero-icon{width:78px;height:78px;display:grid;place-items:center;background:rgba(255,255,255,.13);border-radius:22px;color:#fff;font-size:2.5rem}.training-card{transition:.2s}.training-card:hover{transform:translateY(-4px)}.training-title{min-height:48px}.date{font-size:.78rem;color:#697a8d;white-space:nowrap}.progress{height:9px;border-radius:10px}.progress-bar{background:linear-gradient(90deg,#696cff,#38b6ff)}@media(max-width:576px){.hero-icon{display:none}.card-footer{align-items:flex-start!important;gap:.75rem;flex-direction:column}}</style>@endpush
