@extends('layouts.master')
@section('title','Manajemen Mutu')
@section('content')
<div class="container-xxl container-p-y">
 <div class="qm-hero mb-4"><div><span class="eyebrow"><i class="bx bx-check-shield"></i> KENDALI KELENGKAPAN</span><h3 class="text-white fw-bold mt-2 mb-1">Manajemen Mutu Pelatihan</h3><p class="mb-0 text-white-50">Pantau kelengkapan dokumen setiap pelatihan secara terstruktur dan mudah dibaca.</p></div><div class="hero-icon"><i class="bx bx-folder-open"></i></div></div>
 @if(session('success'))<div class="alert alert-success"><i class="bx bx-check-circle me-1"></i>{{session('success')}}</div>@endif
 <div class="card filter-card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex align-items-center gap-2 mb-3"><span class="filter-icon"><i class="bx bx-filter-alt"></i></span><div><h6 class="fw-bold mb-0">Cari dan Filter Pelatihan</h6><small class="text-muted">Temukan pelatihan berdasarkan nama atau bidang penyelenggara.</small></div></div><form class="row g-3 align-items-end"><div class="col-lg-6"><label class="form-label fw-semibold">Nama pelatihan</label><div class="input-group"><span class="input-group-text bg-white"><i class="bx bx-search"></i></span><input name="search" value="{{request('search')}}" class="form-control" placeholder="Ketik nama pelatihan..."></div></div><div class="col-lg-4"><label class="form-label fw-semibold">Bidang penyelenggara</label><select name="bidang" class="form-select" @disabled(auth()->user()->role==='admin_bidang')><option value="">Semua bidang</option>@foreach($bidangs as $bidang)<option value="{{$bidang}}" @selected(request('bidang')===$bidang)>{{$bidang}}</option>@endforeach</select></div><div class="col-lg-2 d-flex gap-2"><button class="btn btn-primary flex-grow-1"><i class="bx bx-search me-1"></i>Cari</button><a href="{{route('quality-management.index')}}" class="btn btn-outline-secondary" title="Reset filter"><i class="bx bx-reset"></i></a></div></form></div></div>
 @php
     $completeOnPage = $trainings->filter(function($item) use ($totalRequirements) { $required=max(0,$totalRequirements-$item->quality_not_required_count); return $required===0 || $item->quality_completed_count >= $required; })->count();
     $averageOnPage = $trainings->count() ? round($trainings->avg(function($item) use ($totalRequirements) { $required=max(0,$totalRequirements-$item->quality_not_required_count); return $required ? min(100,$item->quality_completed_count/$required*100) : 100; })) : 0;
 @endphp
 <div class="row g-3 mb-4"><div class="col-md-4"><div class="summary-card"><span class="summary-icon primary"><i class="bx bx-book-open"></i></span><div><small>Pelatihan ditampilkan</small><strong>{{$trainings->count()}}</strong></div></div></div><div class="col-md-4"><div class="summary-card"><span class="summary-icon success"><i class="bx bx-check-circle"></i></span><div><small>Kelengkapan selesai</small><strong>{{$completeOnPage}}</strong></div></div></div><div class="col-md-4"><div class="summary-card"><span class="summary-icon info"><i class="bx bx-line-chart"></i></span><div><small>Rata-rata progres</small><strong>{{$averageOnPage}}%</strong></div></div></div></div>
 <div class="row g-3">@forelse($trainings as $training)
 @php
     $requiredTotal = max(0, $totalRequirements - $training->quality_not_required_count);
     $percent = $requiredTotal ? round($training->quality_completed_count / $requiredTotal * 100) : 100;
 @endphp
 <div class="col-md-6 col-xl-4"><article class="card training-card h-100 border-0 shadow-sm"><div class="card-body p-4"><div class="training-meta mb-3"><span class="field-badge"><i class="bx bx-buildings"></i><span>{{$training->bidang ?: 'Bidang belum ditentukan'}}</span></span><span class="date"><i class="bx bx-calendar"></i>{{optional($training->tgl_mulai ? \Carbon\Carbon::parse($training->tgl_mulai):null)->translatedFormat('d M Y') ?: '-'}}</span></div><h5 class="fw-bold training-title mb-3" title="{{$training->nama_pelatihan}}">{{$training->nama_pelatihan}}</h5><div class="status-strip {{ $percent===100 ? 'is-complete' : '' }}"><span><i class="bx {{$percent===100?'bx-check-circle':'bx-time-five'}}"></i>{{ $percent===100 ? 'Dokumen wajib lengkap' : ($requiredTotal-$training->quality_completed_count).' dokumen belum tersedia' }}</span><strong>{{$percent}}%</strong></div><div class="progress mt-3"><div class="progress-bar" style="width:{{$percent}}%"></div></div><div class="document-stats mt-3"><div><strong>{{$training->quality_completed_count}}</strong><small>Terunggah</small></div><div><strong>{{$requiredTotal}}</strong><small>Wajib</small></div><div><strong>{{$training->quality_not_required_count}}</strong><small>Tidak berlaku</small></div></div></div><div class="card-footer bg-white border-top p-3"><a href="{{route('quality-management.show',$training)}}" class="btn btn-primary w-100">Kelola Dokumen <i class="bx bx-right-arrow-alt ms-1"></i></a></div></article></div>
 @empty <div class="col-12"><div class="card border-0 shadow-sm"><div class="card-body text-center py-5"><i class="bx bx-folder-open display-3 text-muted"></i><h5 class="mt-3">Pelatihan tidak ditemukan</h5><p class="text-muted mb-0">Coba ubah kata pencarian atau filter bidang.</p></div></div></div>@endforelse</div>
 @if($trainings->hasPages())<div class="mt-4">{{$trainings->links()}}</div>@endif
</div>
@endsection
@push('css')<style>.qm-hero{background:linear-gradient(125deg,#224a9b,#587ee8);padding:2rem;border-radius:20px;display:flex;align-items:center;justify-content:space-between;box-shadow:0 16px 35px rgba(34,74,155,.2)}.eyebrow{font-size:.72rem;letter-spacing:.12em;color:#dce8ff}.hero-icon{width:78px;height:78px;display:grid;place-items:center;background:rgba(255,255,255,.13);border-radius:22px;color:#fff;font-size:2.5rem;flex:0 0 auto}.filter-card{border-radius:16px}.filter-icon{width:42px;height:42px;display:grid;place-items:center;border-radius:12px;background:#eaf0ff;color:#4164cb;font-size:21px}.summary-card{height:100%;display:flex;align-items:center;gap:14px;padding:18px;border:1px solid #e5eaf2;border-radius:15px;background:#fff;box-shadow:0 5px 18px rgba(37,62,110,.05)}.summary-card small,.summary-card strong{display:block}.summary-card small{color:#7a8495}.summary-card strong{font-size:1.45rem;color:#25334d}.summary-icon{width:46px;height:46px;display:grid;place-items:center;border-radius:13px;font-size:23px}.summary-icon.primary{background:#eaf0ff;color:#4164cb}.summary-icon.success{background:#e8f8ef;color:#28a769}.summary-icon.info{background:#e5f7fb;color:#1c9abb}.training-card{border-radius:16px;overflow:hidden;transition:.2s}.training-card:hover{transform:translateY(-4px);box-shadow:0 15px 35px rgba(39,62,110,.12)!important}.training-meta{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.field-badge{display:inline-flex;align-items:flex-start;gap:6px;min-width:0;max-width:68%;padding:7px 9px;border-radius:9px;background:#edf2ff;color:#3759b3;font-size:.72rem;line-height:1.3}.field-badge span{display:-webkit-box;overflow:hidden;-webkit-line-clamp:2;-webkit-box-orient:vertical}.date{display:flex;align-items:center;gap:4px;font-size:.72rem;color:#697a8d;white-space:nowrap}.training-title{display:-webkit-box;min-height:50px;overflow:hidden;-webkit-line-clamp:2;-webkit-box-orient:vertical;line-height:1.45}.status-strip{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 11px;border-radius:10px;background:#fff5e6;color:#a86b12;font-size:.78rem}.status-strip span{display:flex;align-items:center;gap:5px;min-width:0}.status-strip.is-complete{background:#eaf8f0;color:#228759}.progress{height:8px;border-radius:10px}.progress-bar{background:linear-gradient(90deg,#696cff,#38b6ff)}.document-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.document-stats div{text-align:center;padding:9px 5px;border-radius:9px;background:#f7f8fb}.document-stats strong,.document-stats small{display:block}.document-stats strong{font-size:1rem;color:#2c3c58}.document-stats small{font-size:.65rem;color:#8490a3}@media(max-width:576px){.qm-hero{padding:1.5rem}.hero-icon{display:none}.training-meta{flex-direction:column}.field-badge{max-width:100%}.date{white-space:normal}}</style>@endpush
