@extends('layouts.auth')
@section('title','Pendaftaran Magang/PKL')
@section('content')
<style>
:root{--intern-primary:#27708e;--intern-dark:#183f54;--intern-soft:#edf7fa}
body{background:linear-gradient(145deg,#f5fafc 0%,#eef3ff 100%);min-height:100vh;color:#344054}
.register-wrap{max-width:900px;margin:auto;padding:28px 12px 64px}
.brand-box{display:inline-flex;align-items:center;gap:10px;background:#fff;border:1px solid #e6ebf0;border-radius:30px;padding:8px 15px;box-shadow:0 4px 18px rgba(34,48,62,.06)}
.brand-box img{width:34px;height:34px;object-fit:contain}.brand-box strong{color:#344054;letter-spacing:.08em}
.register-hero{border:0;border-radius:22px;background:linear-gradient(125deg,var(--intern-dark),#28677f 55%,#4f9db9);color:#fff;overflow:hidden;position:relative;box-shadow:0 14px 36px rgba(33,78,103,.22)}
.register-hero:after{content:"";position:absolute;width:260px;height:260px;border-radius:50%;background:rgba(255,255,255,.08);right:-80px;top:-150px}
.register-hero .card-body{position:relative;z-index:1}.register-hero h2{color:#fff!important;line-height:1.3;margin-bottom:10px}
.hero-kicker{display:inline-flex!important;background:#fff!important;color:#215d75!important;border:0!important;padding:8px 13px!important;border-radius:30px!important;font-weight:700}
.hero-description{color:rgba(255,255,255,.82)!important;line-height:1.65}
.hero-meta{display:inline-flex;align-items:center;gap:6px;background:rgba(255,255,255,.14)!important;border:1px solid rgba(255,255,255,.22)!important;color:#fff!important;padding:8px 12px!important;border-radius:30px!important;font-weight:500;white-space:normal;text-align:left}
.registration-guide{border:1px solid #cce2eb;background:#f3fbfe;border-radius:16px;color:#285668}
.register-card{border:0;border-radius:19px;box-shadow:0 8px 30px rgba(34,48,62,.08);overflow:hidden}.register-card .card-body{background:#fff}
.step-title{display:flex;align-items:flex-start;gap:12px;font-weight:700;color:#26394a}.step-number{width:36px;height:36px;border-radius:11px;background:var(--intern-soft);color:var(--intern-primary);display:flex;align-items:center;justify-content:center;flex:0 0 auto}
.form-label{font-weight:600;color:#344054;margin-bottom:7px}.form-control,.input-group-text{min-height:46px;border-color:#d9e0e7;border-radius:11px}.form-control:focus{border-color:#62a3bc;box-shadow:0 0 0 .2rem rgba(79,157,185,.14)}
.password-toggle{border-left:0;background:#f8fafb;color:#27708e}.submit-registration{background:linear-gradient(90deg,#246a86,#4f9db9);border:0;border-radius:12px;box-shadow:0 8px 20px rgba(39,112,142,.24)}
.closed-registration{border:0;border-radius:17px;box-shadow:0 7px 25px rgba(34,48,62,.08)}
@media(max-width:575.98px){.register-wrap{padding:18px 4px 45px}.register-hero{border-radius:17px}.register-hero .card-body,.register-card .card-body{padding:21px!important}.hero-meta{width:100%;border-radius:12px!important}.step-title small{line-height:1.35}.form-control{font-size:16px}}
</style>
<div class="register-wrap">
<div class="text-center mb-4"><div class="brand-box"><img src="{{asset('assets/img/favicon/inte.png')}}" alt="INTEGRAL"><strong>INTEGRAL</strong></div></div>
<div class="card register-hero mb-4"><div class="card-body p-4 p-md-5">
<span class="badge hero-kicker mb-3"><i class="bx bx-briefcase-alt-2 me-1"></i>Pendaftaran Magang/PKL</span>
<h2 class="fw-bold">{{$program->title}}</h2>
@if($program->description)<p class="hero-description mb-4">{{$program->description}}</p>@endif
<div class="d-flex flex-column flex-sm-row flex-wrap gap-2">
<span class="hero-meta"><i class="bx bx-building"></i><span>{{$program->bidang?:'BPSDM Provinsi Jawa Barat'}}</span></span>
@if($program->registration_closes_at)<span class="hero-meta"><i class="bx bx-time"></i><span>Batas pendaftaran {{$program->registration_closes_at->translatedFormat('d F Y')}}</span></span>@endif
</div></div></div>
@if(!$program->isRegistrationOpen())<div class="alert alert-warning closed-registration text-center p-4 p-md-5"><i class="bx bx-lock-alt fs-1"></i><h5 class="mt-2">Pendaftaran belum tersedia</h5><p class="mb-0">Silakan hubungi pengelola program magang.</p></div>@else
@if($errors->any())<div class="alert alert-danger"><strong>Periksa kembali data:</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $e)<li>{{$e}}</li>@endforeach</ul></div>@endif
<div class="registration-guide p-3 p-md-4 mb-4"><div class="d-flex gap-3"><i class="bx bx-info-circle fs-3 text-info"></i><div><strong class="d-block mb-1">Sebelum mengisi formulir</strong><span class="small">Siapkan data sekolah/kampus. NIS/NIM otomatis menjadi username, sedangkan password dibuat sendiri oleh peserta. Akun dapat digunakan setelah disetujui pengelola.</span></div></div></div>
<form method="POST" action="{{route('internships.public.store',$program->public_token)}}" class="card register-card"><div class="card-body p-4 p-md-5">@csrf
<div class="step-title mb-3"><span class="step-number">1</span><div>Identitas Peserta<small class="d-block text-muted fw-normal">Isi sesuai data resmi sekolah atau kampus.</small></div></div><div class="row g-3 mb-4"><div class="col-md-6"><label class="form-label">Nama lengkap *</label><input name="name" value="{{old('name')}}" class="form-control" required></div><div class="col-md-6"><label class="form-label">NIS/NIM *</label><input id="studentNumber" name="student_number" value="{{old('student_number')}}" class="form-control" required><small class="text-primary"><i class="bx bx-user me-1"></i>NIS/NIM ini otomatis menjadi username login.</small></div><div class="col-md-6"><label class="form-label">Jurusan *</label><input name="major" value="{{old('major')}}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Sekolah/Kampus *</label><input name="institution" value="{{old('institution')}}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Unit/Bidang Penempatan *</label><input name="placement_unit" value="{{old('placement_unit')}}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Email *</label><input type="email" name="email" value="{{old('email')}}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Tanggal mulai *</label><input type="date" name="start_date" value="{{old('start_date')}}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Tanggal selesai *</label><input type="date" name="end_date" value="{{old('end_date')}}" class="form-control" required></div></div>
<hr class="my-4"><div class="step-title mb-3"><span class="step-number">2</span><div>Buat Akun INTEGRAL<small class="d-block text-muted fw-normal">Akun dapat digunakan setelah disetujui pengelola.</small></div></div><div class="row g-3"><div class="col-12"><label class="form-label">Username Login</label><div class="input-group"><span class="input-group-text"><i class="bx bx-id-card"></i></span><input id="generatedUsername" value="{{old('student_number')}}" class="form-control bg-light" placeholder="Terisi otomatis dari NIS/NIM" readonly></div><small class="text-muted">Tidak perlu membuat username baru. Gunakan NIS/NIM saat login.</small></div><div class="col-md-6"><label class="form-label">Password *</label><div class="input-group"><input id="internPassword" type="password" name="password" minlength="8" class="form-control" required><button type="button" class="input-group-text password-toggle"><i class="bx bx-show"></i></button></div></div><div class="col-md-6"><label class="form-label">Konfirmasi password *</label><input type="password" name="password_confirmation" minlength="8" class="form-control" required></div></div><div class="alert alert-info small mt-4"><i class="bx bx-info-circle me-1"></i>Username Anda adalah <strong>NIS/NIM</strong>. Password dibuat sendiri di atas. Simpan keduanya untuk login setelah pendaftaran disetujui.</div><button class="btn btn-primary btn-lg w-100 submit-registration"><i class="bx bx-send me-1"></i>Kirim Pendaftaran</button></div></form>
@endif</div>
<script>const studentNumber=document.getElementById('studentNumber'),generatedUsername=document.getElementById('generatedUsername');studentNumber?.addEventListener('input',()=>generatedUsername.value=studentNumber.value.trim());document.querySelector('.password-toggle')?.addEventListener('click',function(){const i=document.getElementById('internPassword'),show=i.type==='password';i.type=show?'text':'password';this.querySelector('i').className=show?'bx bx-hide':'bx bx-show'});</script>
@endsection