@extends('layouts.master')
@section('title','ID Card Pelatihan')
@section('content')
@php
$logoUrl=$setting->logo_path?Storage::url($setting->logo_path):null;
$backgroundUrl=$setting->background_path?Storage::url($setting->background_path):null;
$photoUrl=$card->photo_path?Storage::url($card->photo_path):($participant->pasFotoFile?->file_path?Storage::url($participant->pasFotoFile->file_path):($participant->user?->profile_photo?Storage::url($participant->user->profile_photo):null));
@endphp
<div class="container-xxl container-p-y">
 <div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4"><div><a href="{{route('participant.training.show',['id'=>$training->id,'tab'=>'idcard'])}}" class="small text-muted"><i class="bx bx-arrow-back"></i> Kembali ke detail pelatihan</a><h4 class="fw-bold mt-2 mb-1">ID Card Peserta</h4><p class="text-muted mb-0">Atur foto, periksa data, lalu unduh kartu siap cetak.</p></div><div class="d-flex gap-2 align-items-start"><div class="dropdown"><button class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown"><i class="bx bx-image me-1"></i>Unduh Gambar</button><div class="dropdown-menu"><a class="dropdown-item" href="{{route('participant.identity-card.image',[$training,'format'=>'png'])}}"><i class="bx bx-image me-2"></i>Format PNG</a><a class="dropdown-item" href="{{route('participant.identity-card.image',[$training,'format'=>'jpg'])}}"><i class="bx bx-photo-album me-2"></i>Format JPG</a></div></div><a href="{{route('participant.identity-card.pdf',$training)}}" class="btn btn-primary"><i class="bx bx-download me-1"></i>Unduh PDF</a></div></div>
 @if(session('success'))<div class="alert alert-success"><i class="bx bx-check-circle me-1"></i>{{session('success')}}</div>@endif
 @if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif
 <div class="row g-4"><div class="col-xl-8"><div class="card border-0 shadow-sm"><div class="card-header border-bottom d-flex justify-content-between"><div><h5 class="fw-bold mb-1">Preview ID Card</h5><small class="text-muted">Ukuran cetak 9,2 × 12,4 cm portrait.</small></div><span class="badge bg-label-success">Siap dicetak</span></div><div class="card-body preview-shell">@include('identity-cards.card')</div></div></div>
 <div class="col-xl-4"><div class="card border-0 shadow-sm mb-4"><div class="card-header border-bottom"><h5 class="fw-bold mb-1">Foto ID Card</h5><small class="text-muted">Perubahan hanya berlaku pada ID card ini.</small></div><form method="POST" enctype="multipart/form-data" action="{{route('participant.identity-card.photo',$training)}}" id="photoForm">@csrf @method('PUT')<div class="card-body"><input type="file" name="photo" id="photoInput" accept="image/jpeg,image/png,image/webp" class="form-control mb-3"><div class="crop-stage"><canvas id="cropCanvas" width="600" height="800"></canvas><div id="cropEmpty" class="crop-empty @if($photoUrl)d-none @endif"><i class="bx bx-image-add"></i><span>Pilih foto untuk mulai mengatur</span></div></div><div class="mt-3"><label class="form-label d-flex justify-content-between"><span>Perbesar foto</span><span id="zoomLabel">100%</span></label><input type="range" id="cropZoom" min="100" max="220" value="100" class="form-range"></div><div class="row g-2"><div class="col-6"><label class="form-label small">Geser horizontal</label><input type="range" id="cropX" min="-100" max="100" value="0" class="form-range"></div><div class="col-6"><label class="form-label small">Geser vertikal</label><input type="range" id="cropY" min="-100" max="100" value="0" class="form-range"></div></div><div class="alert alert-info small py-2 mb-0"><i class="bx bx-shield me-1"></i>Rasio otomatis 3:4 dan foto profil utama tidak berubah.</div></div><div class="card-footer border-top d-grid"><button class="btn btn-primary" id="savePhoto"><i class="bx bx-crop me-1"></i>Simpan Foto ID Card</button></div></form></div>
 <div class="card border-0 shadow-sm"><div class="card-body"><h6 class="fw-bold">Data yang ditampilkan</h6><dl class="row small mb-0"><dt class="col-4 text-muted">Nama</dt><dd class="col-8 fw-semibold">{{$participant->name}}</dd><dt class="col-4 text-muted">Jabatan</dt><dd class="col-8">{{$participant->jabatan?:'-'}}</dd><dt class="col-4 text-muted">Instansi</dt><dd class="col-8">{{$participant->instansi?:'-'}}</dd></dl><small class="text-muted">Jika data tidak sesuai, perbarui profil Anda.</small></div></div></div></div>
</div>
@include('identity-cards.styles')
<style>.crop-stage{position:relative;width:210px;max-width:100%;aspect-ratio:3/4;margin:auto;overflow:hidden;border:2px dashed #c9ced8;border-radius:12px;background:#eef1f5}.crop-stage canvas{display:block;width:100%;height:100%}.crop-empty{position:absolute;inset:0;display:grid;place-content:center;gap:.4rem;color:#8592a3;text-align:center}.crop-empty i{font-size:2.5rem}</style>
@endsection
@push('js')

<script>
const canvas=document.getElementById('cropCanvas'),ctx=canvas.getContext('2d'),input=document.getElementById('photoInput'),zoom=document.getElementById('cropZoom'),moveX=document.getElementById('cropX'),moveY=document.getElementById('cropY');let cropImage=new Image();cropImage.crossOrigin='anonymous';
function drawCrop(){if(!cropImage.naturalWidth)return;const cover=Math.max(canvas.width/cropImage.naturalWidth,canvas.height/cropImage.naturalHeight);const scale=cover*(zoom.value/100);const w=cropImage.naturalWidth*scale,h=cropImage.naturalHeight*scale;const x=(canvas.width-w)/2+(moveX.value/100)*(w-canvas.width)/2;const y=(canvas.height-h)/2+(moveY.value/100)*(h-canvas.height)/2;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(cropImage,x,y,w,h);document.getElementById('zoomLabel').textContent=zoom.value+'%';document.getElementById('cropEmpty').classList.add('d-none');}
@if($photoUrl) cropImage.src=@json(asset($photoUrl)); cropImage.onload=drawCrop; @endif
input.addEventListener('change',()=>{const file=input.files[0];if(!file)return;cropImage=new Image();cropImage.onload=drawCrop;cropImage.src=URL.createObjectURL(file)});[zoom,moveX,moveY].forEach(el=>el.addEventListener('input',drawCrop));
document.getElementById('photoForm').addEventListener('submit',e=>{if(!cropImage.naturalWidth){e.preventDefault();alert('Pilih foto terlebih dahulu.');return;}e.preventDefault();canvas.toBlob(blob=>{const file=new File([blob],'foto-idcard.jpg',{type:'image/jpeg'});const dt=new DataTransfer();dt.items.add(file);input.files=dt.files;e.target.submit();},'image/jpeg',.92)});
</script>
@endpush