<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::create('electronic_signature_requests',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('title');$t->text('description')->nullable();$t->string('bidang')->nullable();$t->string('status',30)->default('in_progress');$t->foreignId('created_by');$t->foreign('created_by','es_request_creator_fk')->references('id')->on('users')->restrictOnDelete();$t->timestamp('completed_at')->nullable();$t->timestamps();$t->index(['bidang','status']);});
  Schema::create('electronic_signature_documents',function(Blueprint $t){$t->id();$t->foreignId('electronic_signature_request_id');$t->foreign('electronic_signature_request_id','es_doc_request_fk')->references('id')->on('electronic_signature_requests')->cascadeOnDelete();$t->string('original_name');$t->string('original_path');$t->string('current_path');$t->string('final_path')->nullable();$t->unsignedBigInteger('file_size')->default(0);$t->string('status',30)->default('waiting');$t->timestamp('completed_at')->nullable();$t->timestamps();});
  Schema::create('electronic_signature_actors',function(Blueprint $t){$t->id();$t->foreignId('electronic_signature_request_id');$t->foreign('electronic_signature_request_id','es_actor_request_fk')->references('id')->on('electronic_signature_requests')->cascadeOnDelete();$t->foreignId('user_id');$t->foreign('user_id','es_actor_user_fk')->references('id')->on('users')->restrictOnDelete();$t->string('role',20);$t->unsignedSmallInteger('sequence');$t->timestamps();$t->unique(['electronic_signature_request_id','sequence'],'es_actor_sequence_unique');$t->unique(['electronic_signature_request_id','user_id'],'es_actor_user_unique');});
  Schema::create('electronic_signature_actions',function(Blueprint $t){$t->id();$t->foreignId('electronic_signature_document_id');$t->foreign('electronic_signature_document_id','es_action_document_fk')->references('id')->on('electronic_signature_documents')->cascadeOnDelete();$t->foreignId('electronic_signature_actor_id');$t->foreign('electronic_signature_actor_id','es_action_actor_fk')->references('id')->on('electronic_signature_actors')->cascadeOnDelete();$t->string('status',20)->default('waiting');$t->timestamp('signed_at')->nullable();$t->text('error_message')->nullable();$t->timestamps();$t->unique(['electronic_signature_document_id','electronic_signature_actor_id'],'es_document_actor_unique');});
  Schema::create('electronic_signature_attempts',function(Blueprint $t){$t->id();$t->foreignId('electronic_signature_action_id');$t->foreign('electronic_signature_action_id','es_attempt_action_fk')->references('id')->on('electronic_signature_actions')->cascadeOnDelete();$t->foreignId('user_id');$t->foreign('user_id','es_attempt_user_fk')->references('id')->on('users')->restrictOnDelete();$t->boolean('successful')->default(false);$t->string('response_code',50)->nullable();$t->text('message')->nullable();$t->unsignedInteger('duration_ms')->nullable();$t->string('ip_address',45)->nullable();$t->timestamps();$t->index(['electronic_signature_action_id','created_at'],'es_attempt_action_index');});
 }
 public function down():void{Schema::dropIfExists('electronic_signature_attempts');Schema::dropIfExists('electronic_signature_actions');Schema::dropIfExists('electronic_signature_actors');Schema::dropIfExists('electronic_signature_documents');Schema::dropIfExists('electronic_signature_requests');}
};