@extends('layouts.master')
@section('title','Portal Mitra')
@section('content')
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4">
    <div><h4 class="fw-bold mb-1">Pengajuan Mitra</h4><p class="text-muted mb-0">Pantau seluruh pengajuan, revisi, dan dokumen final dari satu halaman.</p></div>
    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#chooseSubmissionType"><i class="bx bx-plus me-1"></i>Buat Pengajuan</button>
</div>

<div class="card border-0 shadow-sm bg-label-primary mb-4"><div class="card-body p-4"><div class="row align-items-center g-3"><div class="col-lg-5"><h5 class="fw-bold mb-1">Alur pengajuan yang sederhana</h5><p class="text-muted mb-0">Siapkan surat permohonan, pilih jenis pengajuan, lalu pantau pembahasan sampai dokumen final.</p></div><div class="col-lg-7"><div class="d-flex flex-wrap justify-content-lg-end gap-2"><span class="badge bg-white text-primary p-2"><i class="bx bx-upload me-1"></i>1. Surat Permohonan</span><span class="badge bg-white text-primary p-2"><i class="bx bx-send me-1"></i>2. Kirim Pengajuan</span><span class="badge bg-white text-primary p-2"><i class="bx bx-conversation me-1"></i>3. Diskusi/Revisi</span><span class="badge bg-white text-success p-2"><i class="bx bx-check-shield me-1"></i>4. Final</span></div></div></div></div></div>

<div class="row g-3 mb-4">
@foreach([['','Semua',$stats['all'],'bx-folder','primary'],['draft','Draft',$stats['draft'],'bx-edit','secondary'],['process','Dalam Proses',$stats['process'],'bx-loader-circle','info'],['revision_requested','Perlu Revisi',$stats['revision'],'bx-error-circle','warning'],['final','Final',$stats['final'],'bx-check-shield','success']] as [$key,$label,$value,$icon,$color])
<div class="col-6 col-xl"><a href="{{route('mitra.dashboard',array_filter(['status'=>$key,'type'=>request('type'),'search'=>request('search')]))}}" class="card border-0 shadow-sm h-100 text-decoration-none {{request('status','')===$key?'border border-'.$color:''}}"><div class="card-body d-flex align-items-center gap-3 p-3"><span class="avatar-initial rounded bg-label-{{$color}} p-2"><i class="bx {{$icon}} fs-4"></i></span><div><h5 class="mb-0 text-dark">{{$value}}</h5><small class="text-muted">{{$label}}</small></div></div></a></div>
@endforeach
</div>

<div class="card border-0 shadow-sm">
    <div class="card-header border-bottom d-flex flex-column flex-lg-row justify-content-between gap-3"><div><h5 class="mb-1">Daftar Pengajuan</h5><small class="text-muted">Menampilkan pengajuan terbaru terlebih dahulu.</small></div><form method="GET" class="d-flex flex-wrap gap-2"><input name="search" class="form-control" value="{{request('search')}}" placeholder="Cari judul..." style="max-width:220px"><select name="type" class="form-select" style="max-width:190px"><option value="">Semua jenis</option><option value="training" @selected(request('type')==='training')>Pelatihan</option><option value="cooperation" @selected(request('type')==='cooperation')>Kerja Sama</option></select>@if(request('status'))<input type="hidden" name="status" value="{{request('status')}}">@endif<button class="btn btn-outline-primary"><i class="bx bx-search"></i></button>@if(request()->hasAny(['search','type','status']))<a href="{{route('mitra.dashboard')}}" class="btn btn-outline-secondary"><i class="bx bx-x"></i></a>@endif</form></div>
    <div class="table-responsive"><table class="table table-hover align-middle"><thead class="table-light"><tr><th>Pengajuan</th><th>Tujuan</th><th>Status</th><th>Aktivitas</th><th class="text-end">Aksi</th></tr></thead><tbody>
    @forelse($submissions as $s)@php $color=$s->status==='final'?'success':($s->status==='revision_requested'?'warning':($s->status==='draft'?'secondary':'primary')); @endphp<tr><td><div class="d-flex align-items-center gap-3"><span class="avatar-initial rounded bg-label-{{$s->type==='training'?'primary':'warning'}}"><i class="bx {{$s->type==='training'?'bx-book-open':'bx-handshake'}}"></i></span><div><strong class="d-block">{{$s->title}}</strong><small class="text-muted">{{$s->type_label}} · {{$s->created_at->translatedFormat('d M Y')}}</small></div></div></td><td class="text-wrap" style="max-width:270px"><small>{{$s->target_bidang}}</small></td><td><span class="badge bg-label-{{$color}}">{{$s->status_label}}</span></td><td><small class="d-block">{{$s->documents_count}} dokumen/versi</small><small class="text-muted">Diperbarui {{$s->updated_at->diffForHumans()}}</small></td><td class="text-end"><a href="{{route('mitra.submissions.show',$s)}}" class="btn btn-sm btn-primary">Buka <i class="bx bx-chevron-right"></i></a></td></tr>
    @empty<tr><td colspan="5"><div class="text-center py-5"><span class="avatar-initial rounded-circle bg-label-primary d-inline-flex p-3 mb-3"><i class="bx bx-file-blank fs-2"></i></span><h6 class="fw-bold">Belum ada pengajuan</h6><p class="text-muted mb-3">Buat pengajuan pertama Anda melalui tombol di atas.</p><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#chooseSubmissionType">Buat Pengajuan</button></div></td></tr>@endforelse
    </tbody></table></div>
    @if($submissions->hasPages())<div class="card-footer d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-2"><small class="text-muted">Menampilkan {{$submissions->firstItem()}}–{{$submissions->lastItem()}} dari {{$submissions->total()}} pengajuan</small>{{$submissions->onEachSide(1)->links()}}</div>@endif
</div>

<div class="modal fade" id="chooseSubmissionType" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><div><h5 class="modal-title">Pilih Jenis Pengajuan</h5><small class="text-muted">Anda akan diarahkan ke formulir yang sesuai.</small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body p-4"><div class="d-grid gap-3"><a href="{{route('mitra.submissions.create','training')}}" class="border rounded p-3 text-decoration-none d-flex gap-3 align-items-center submission-choice"><span class="avatar-initial rounded bg-label-primary p-2"><i class="bx bx-book-add fs-4"></i></span><div><strong class="text-dark d-block">Pengajuan Pelatihan</strong><small class="text-muted">Untuk bidang Teknis Inti, Teknis Umum, atau Manajerial.</small></div><i class="bx bx-chevron-right ms-auto"></i></a><a href="{{route('mitra.submissions.create','cooperation')}}" class="border rounded p-3 text-decoration-none d-flex gap-3 align-items-center submission-choice"><span class="avatar-initial rounded bg-label-warning p-2"><i class="bx bx-handshake fs-4"></i></span><div><strong class="text-dark d-block">Pengajuan Kerja Sama</strong><small class="text-muted">Otomatis ditujukan kepada bidang SKPK.</small></div><i class="bx bx-chevron-right ms-auto"></i></a></div><div class="alert alert-info small mt-3 mb-0"><i class="bx bx-info-circle me-1"></i>Siapkan surat permohonan dalam format PDF atau Word.</div></div></div></div></div>
@endsection
@push('css')<style>.submission-choice{transition:.2s}.submission-choice:hover{border-color:#696cff!important;background:#f7f7ff;transform:translateY(-2px)}</style>@endpush