@extends('layouts.master')
@section('title','Pengajuan Mitra')
@section('content')
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4"><div><h4 class="fw-bold mb-1">Pengajuan Mitra</h4><p class="text-muted mb-0">Periksa pengajuan yang ditujukan kepada bidang Anda dan pantau pertukaran draft.</p></div><form method="GET" class="d-flex flex-wrap gap-2"><input name="search" class="form-control" value="{{request('search')}}" placeholder="Cari judul atau mitra"><select name="type" class="form-select"><option value="">Semua jenis</option><option value="training" @selected(request('type')==='training')>Pelatihan</option><option value="cooperation" @selected(request('type')==='cooperation')>Kerja Sama</option></select><select name="status" class="form-select"><option value="">Semua flag</option><option value="draft" @selected(request('status')==='draft')>Draft</option><option value="process" @selected(request('status')==='process')>Dalam Pembahasan</option><option value="final" @selected(request('status')==='final')>Final</option></select><button class="btn btn-primary"><i class="bx bx-filter-alt"></i></button>@if(request()->hasAny(['search','type','status']))<a href="{{route('mitra.admin.index')}}" class="btn btn-outline-secondary"><i class="bx bx-x"></i></a>@endif</form></div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle"><thead class="table-light"><tr><th>Mitra & Pengajuan</th><th>Jenis</th><th>Bidang Tujuan</th><th>Status</th><th>PIC/Dokumen</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($submissions as $s)@php $color=$s->status==='final'?'success':($s->status==='revision_requested'?'warning':($s->status==='rejected'?'danger':($s->status==='draft'?'secondary':'primary'))); @endphp<tr><td><strong class="d-block">{{$s->title}}</strong><small class="text-muted">{{$s->partner->instansi?:$s->partner->name}} · {{$s->created_at->translatedFormat('d M Y')}}</small></td><td><span class="badge bg-label-info">{{$s->type_label}}</span></td><td class="text-wrap" style="max-width:260px">{{$s->target_bidang}}</td><td>
@if($s->status==='final')<span class="badge bg-success"><i class="bx bx-check-shield me-1"></i>FINAL</span>
@elseif($s->status==='draft')<span class="badge bg-label-secondary"><i class="bx bx-edit me-1"></i>DRAFT</span>
@elseif(in_array($s->status,['submitted','revision_submitted']))<span class="badge bg-warning"><i class="bx bx-bell me-1"></i>PERLU DITINJAU</span>
@else<span class="badge bg-label-primary"><i class="bx bx-conversation me-1"></i>DALAM PEMBAHASAN</span>@endif
</td><td><small class="d-block">{{$s->assignee?->name?:'PIC belum ditentukan'}}</small><small class="text-muted">{{$s->documents_count}} versi dokumen</small></td><td class="text-end"><a href="{{route('mitra.submissions.show',$s)}}" class="btn btn-sm btn-primary"><i class="bx bx-folder-open me-1"></i>Kelola</a></td></tr>@empty<tr><td colspan="6" class="text-center py-5 text-muted"><i class="bx bx-inbox fs-1 d-block mb-2"></i>Tidak ada pengajuan dalam lingkup bidang Anda.</td></tr>@endforelse</tbody></table></div>@if($submissions->hasPages())<div class="card-footer">{{$submissions->links()}}</div>@endif</div>
@endsection