@extends('layouts.master')
@section('title','Kelola Kerja Sama')
@section('content')
@php($size=fn($b)=>$b>=1048576?number_format($b/1048576,1).' MB':number_format($b/1024,1).' KB')
<div class="container-xxl container-p-y">
 <div class="coop-hero mb-4"><div><span><i class="bx bx-handshake"></i> ARSIP KELEMBAGAAN</span><h3 class="text-white fw-bold mt-2 mb-1">Kelola Kerja Sama</h3><p class="text-white-50 mb-0">Dokumen kerja sama Bidang Sertifikasi Kompetensi & Pengelolaan Kelembagaan.</p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-light" href="{{route('cooperations.export',request()->only(['year','search']))}}"><i class="bx bx-spreadsheet"></i> Export Excel</a><button class="btn btn-light text-primary" data-bs-toggle="modal" data-bs-target="#createModal"><i class="bx bx-plus"></i> Tambah Kerja Sama</button></div></div>
 @if(session('success'))<div class="alert alert-success"><i class="bx bx-check-circle me-1"></i>{{session('success')}}</div>@endif
 @if($errors->any())<div class="alert alert-danger"><i class="bx bx-error-circle me-1"></i>{{$errors->first()}}</div>@endif
 <div class="row g-3 mb-4">@foreach([['Total kerja sama',$stats['total'],'bx-folder','primary'],['Tahun '.now()->year,$stats['current_year'],'bx-calendar-check','success'],['Mitra tercatat',$stats['partners'],'bx-buildings','info'],['Cakupan tahun',$stats['years'],'bx-bar-chart','warning']] as $stat)<div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body d-flex gap-3 align-items-center"><span class="avatar-initial rounded bg-label-{{$stat[3]}} p-3"><i class="bx {{$stat[2]}} fs-4"></i></span><div><small class="text-muted">{{$stat[0]}}</small><h3 class="mb-0">{{$stat[1]}}</h3></div></div></div></div>@endforeach</div>
 <div class="card border-0 shadow-sm"><div class="card-header border-bottom"><div class="d-flex flex-column flex-lg-row justify-content-between gap-3"><div><h5 class="fw-bold mb-1">Daftar Kerja Sama</h5><small class="text-muted">Rekap dokumen berdasarkan mitra dan tahun.</small></div><form class="d-flex flex-column flex-sm-row gap-2"><input class="form-control" name="search" value="{{request('search')}}" placeholder="Cari mitra atau tentang..."><select class="form-select" name="year"><option value="">Semua tahun</option>@foreach($years as $y)<option value="{{$y}}" @selected((string)request('year')===(string)$y)>{{$y}}</option>@endforeach</select><button class="btn btn-primary">Cari</button>@if(request()->hasAny(['search','year']))<a class="btn btn-outline-secondary" href="{{route('cooperations.index')}}">Reset</a>@endif</form></div></div>
 <div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Bekerja Sama dengan</th><th>Tentang</th><th>Tahun</th><th>Dokumen</th><th></th></tr></thead><tbody>
 @forelse($records as $item)<tr><td><strong><i class="bx bx-buildings text-primary me-2"></i>{{$item->partner_name}}</strong></td><td class="subject">{{$item->subject}}</td><td><span class="badge bg-label-primary">{{$item->year}}</span></td><td><span class="d-block text-truncate file-label" title="{{$item->original_name}}"><i class="bx {{$item->file_type==='pdf'?'bxs-file-pdf':'bxs-file-doc'}} text-danger me-1"></i>{{$item->original_name}}</span><small class="text-muted">{{$size($item->file_size)}}</small></td><td class="text-end"><div class="d-inline-flex gap-1"><a href="{{route('cooperations.download',$item)}}" class="btn btn-sm btn-outline-primary" title="Unduh"><i class="bx bx-download"></i></a><button class="btn btn-sm btn-outline-warning edit-btn" data-bs-toggle="modal" data-bs-target="#editModal" data-action="{{route('cooperations.update',$item)}}" data-partner="{{$item->partner_name}}" data-subject="{{$item->subject}}" data-year="{{$item->year}}" data-file="{{$item->original_name}}"><i class="bx bx-edit"></i></button><button class="btn btn-sm btn-outline-danger delete-btn" data-bs-toggle="modal" data-bs-target="#deleteModal" data-action="{{route('cooperations.destroy',$item)}}" data-name="{{$item->partner_name}}"><i class="bx bx-trash"></i></button></div></td></tr>@empty<tr><td colspan="5" class="text-center py-5"><i class="bx bx-folder-open fs-1 text-muted"></i><h6 class="mt-2">Belum ada data kerja sama</h6><small class="text-muted">Tambahkan dokumen pertama atau ubah filter.</small></td></tr>@endforelse
 </tbody></table></div>@if($records->hasPages())<div class="card-footer">{{$records->links()}}</div>@endif</div>
</div>
<div class="modal fade" id="createModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><form class="modal-content" method="POST" action="{{route('cooperations.store')}}" enctype="multipart/form-data">@csrf
@include('cooperations.partials.form', ['edit' => false])</form></div></div>
<div class="modal fade" id="editModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><form id="editForm" class="modal-content" method="POST" enctype="multipart/form-data">@csrf
@method('PUT')
@include('cooperations.partials.form', ['edit' => true])</form></div></div>
<div class="modal fade" id="deleteModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form id="deleteForm" class="modal-content" method="POST">@csrf @method('DELETE')<div class="modal-body text-center p-5"><span class="delete-icon"><i class="bx bx-trash"></i></span><h5 class="fw-bold mt-3">Hapus kerja sama?</h5><p class="text-muted">Data dengan <strong id="deleteName"></strong> beserta dokumennya akan dihapus permanen.</p><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button> <button class="btn btn-danger">Ya, Hapus</button></div></form></div></div>
@endsection
@push('css')
<style>.coop-hero{display:flex;align-items:center;justify-content:space-between;gap:2rem;background:linear-gradient(120deg,#284b9b,#4d7de0);border-radius:18px;padding:2rem;box-shadow:0 14px 34px rgba(40,75,155,.2)}.coop-hero>div>span{font-size:.72rem;letter-spacing:.1em;color:#dce8ff}.subject{min-width:240px;max-width:380px}.file-label{max-width:190px}.delete-icon{width:70px;height:70px;display:inline-grid;place-items:center;border-radius:50%;background:#ffe9e9;color:#ff3e1d;font-size:2rem}@media(max-width:767px){.coop-hero{align-items:flex-start;flex-direction:column;padding:1.5rem}}</style>
@endpush
@push('js')
<script>
document.querySelectorAll('.edit-btn').forEach(b=>b.addEventListener('click',()=>{document.getElementById('editForm').action=b.dataset.action;document.getElementById('edit_partner').value=b.dataset.partner;document.getElementById('edit_subject').value=b.dataset.subject;document.getElementById('edit_year').value=b.dataset.year;document.getElementById('current_file').textContent=b.dataset.file;}));
document.querySelectorAll('.delete-btn').forEach(b=>b.addEventListener('click',()=>{document.getElementById('deleteForm').action=b.dataset.action;document.getElementById('deleteName').textContent=b.dataset.name;}));
@if($errors->any()&&old('partner_name')) bootstrap.Modal.getOrCreateInstance(document.getElementById('createModal')).show(); @endif
</script>
@endpush
