<?php
namespace App\Http\Controllers;
use App\Imports\CertificationParticipantImport;
use App\Exports\CertificationYearExport;
use App\Models\CertificationEvent;use App\Models\CertificationParticipant;use App\Models\CertificationType;use App\Models\File;use App\Models\Folder;
use Illuminate\Http\Request;use Illuminate\Support\Facades\Auth;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;use Illuminate\Validation\Rule;use Maatwebsite\Excel\Facades\Excel;use Maatwebsite\Excel\Concerns\FromArray;

class CertificationController extends Controller {
 private const BIDANG='Bidang Sertifikasi Kompetensi & Pengelolaan Kelembagaan';
 private function guard():void{$u=Auth::user();abort_unless($u->role==='superadmin'||($u->role==='admin_bidang'&&$u->bidang===self::BIDANG),403);}
 public function index(){ $this->guard();$types=CertificationType::withCount(['events'])->orderBy('name')->get();$events=CertificationEvent::with('type')->withCount(['participants','participants as graduates_count'=>fn($q)=>$q->where('result','lulus'),'participants as male_count'=>fn($q)=>$q->whereIn('gender',['Laki-laki','Laki-Laki','L','Pria']),'participants as female_count'=>fn($q)=>$q->whereIn('gender',['Perempuan','P','Wanita'])])->latest('start_date')->paginate(12);$stats=['types'=>CertificationType::count(),'events'=>CertificationEvent::count(),'participants'=>CertificationParticipant::count(),'graduates'=>CertificationParticipant::where('result','lulus')->count(),'male'=>CertificationParticipant::whereIn('gender',['Laki-laki','Laki-Laki','L','Pria'])->count(),'female'=>CertificationParticipant::whereIn('gender',['Perempuan','P','Wanita'])->count()];$exportYears=CertificationEvent::query()->selectRaw('YEAR(start_date) as year')->distinct()->orderByDesc('year')->pluck('year');return view('certifications.index',compact('types','events','stats','exportYears')); }
 public function storeType(Request $r){$this->guard();$d=$r->validate(['name'=>'required|string|max:255|unique:certification_types,name']);CertificationType::create($d);return back()->with('success','Jenis sertifikasi berhasil ditambahkan.');}
 public function destroyType(CertificationType $type){$this->guard();if($type->events()->exists())return back()->with('error','Jenis sertifikasi masih digunakan oleh pelaksanaan.');$type->delete();return back()->with('success','Jenis sertifikasi dihapus.');}
 public function storeEvent(Request $r){$this->guard();$d=$r->validate(['certification_type_id'=>'required|exists:certification_types,id','title'=>'required|string|max:255','start_date'=>'required|date','end_date'=>'required|date|after_or_equal:start_date','location'=>'required|string|max:255','supervisor_name'=>'required|string|max:255','supervisor_phone'=>'nullable|string|max:30','supervisor_institution'=>'nullable|string|max:255','participant_quota'=>'required|integer|min:0']);
  $event=DB::transaction(function()use($d){$folders=$this->createFolders($d['title']);return CertificationEvent::create($d+['folder_id'=>$folders['event']->id,'created_by'=>Auth::id()]);});return redirect()->route('certifications.show',$event)->with('success','Pelaksanaan sertifikasi berhasil dibuat.');}
 public function updateEvent(Request $r,CertificationEvent $event){$this->guard();$d=$r->validate(['certification_type_id'=>'required|exists:certification_types,id','title'=>'required|string|max:255','start_date'=>'required|date','end_date'=>'required|date|after_or_equal:start_date','location'=>'required|string|max:255','supervisor_name'=>'required|string|max:255','supervisor_phone'=>'nullable|string|max:30','supervisor_institution'=>'nullable|string|max:255','participant_quota'=>'required|integer|min:0']);DB::transaction(function()use($event,$d){$event->update($d);if($event->folder_id)Folder::whereKey($event->folder_id)->update(['name'=>$d['title']]);});return back()->with('success','Pelaksanaan sertifikasi berhasil diperbarui.');}
 public function show(CertificationEvent $event){$this->guard();$event->load(['type','minutesFile']);$participants=$event->participants()->orderBy('name')->paginate(20);$attempts=CertificationParticipant::whereIn('nip_nik',$participants->pluck('nip_nik'))->whereHas('event',fn($q)=>$q->where('certification_type_id',$event->certification_type_id))->selectRaw("nip_nik, COUNT(*) as attempts, SUM(result = 'tidak_lulus') as failures")->groupBy('nip_nik')->get()->keyBy('nip_nik');return view('certifications.show',compact('event','participants','attempts'));}
 public function import(Request $r,CertificationEvent $event){$this->guard();$r->validate(['file'=>'required|mimes:xlsx,xls|max:10240']);$import=new CertificationParticipantImport($event);Excel::import($import,$r->file('file'));$folder=$this->childFolder($event,'Data Peserta');$this->storeDocument($r->file('file'),$folder);return back()->with('success',"Import selesai: {$import->created} baru, {$import->updated} diperbarui, {$import->skipped} dilewati.");}
 public function destroyParticipant(CertificationParticipant $participant){
  $this->guard();$participant->load('event');$name=$participant->name;$this->purgeParticipants(collect([$participant]));return back()->with('success','Peserta '.$name.' beserta biodata PDF dan tanda tangannya berhasil dihapus.');
 }
 public function destroyAllParticipants(CertificationEvent $event){
  $this->guard();$participants=$event->participants()->get();$count=$participants->count();$extraFiles=collect();$dataFolder=Folder::where('parent_id',$event->folder_id)->where('name','Data Peserta')->first();if($dataFolder)$extraFiles=File::where('folder_id',$dataFolder->id)->get();$this->purgeParticipants($participants,$extraFiles);return back()->with('success',$count.' peserta beserta seluruh biodata, tanda tangan, dan file import peserta berhasil dihapus.');
 }
 private function purgeParticipants($participants,$extraFiles=null):void{
  $extraFiles=$extraFiles?:collect();$fileIds=$participants->pluck('biodata_file_id')->filter()->merge($extraFiles->pluck('id'))->unique()->values();$files=$fileIds->isEmpty()?collect():File::whereIn('id',$fileIds)->get();$paths=$files->pluck('file_path')->merge($participants->pluck('signature_path'))->filter()->unique()->values();$participantIds=$participants->pluck('id')->filter();
  DB::transaction(function()use($participantIds,$fileIds){if($participantIds->isNotEmpty())CertificationParticipant::whereIn('id',$participantIds)->delete();if($fileIds->isNotEmpty())File::whereIn('id',$fileIds)->delete();});
  if($paths->isNotEmpty())Storage::disk('public')->delete($paths->all());
 }
 public function updateResult(Request $r,CertificationParticipant $participant){$this->guard();$d=$r->validate(['result'=>['required',Rule::in(['belum_ditentukan','lulus','tidak_lulus'])],'notes'=>'nullable|string|max:1000']);$participant->update($d);return back()->with('success','Status kelulusan '.$participant->name.' diperbarui.');}
 public function passAllParticipants(CertificationEvent $event){$this->guard();$total=$event->participants()->count();if($total===0)return back()->with('error','Belum ada peserta yang dapat diluluskan.');$updated=$event->participants()->where('result','!=','lulus')->update(['result'=>'lulus','updated_at'=>now()]);return back()->with('success',$updated>0?$updated.' peserta berhasil ditetapkan lulus.':'Seluruh peserta sudah berstatus lulus.');}
 public function uploadMinutes(Request $r,CertificationEvent $event){$this->guard();$r->validate(['file'=>'required|file|mimes:pdf,doc,docx|max:20480']);$folder=$this->childFolder($event,'Berita Acara');$old=$event->minutesFile;$file=$this->storeDocument($r->file('file'),$folder);$event->update(['minutes_file_id'=>$file->id]);if($old){Storage::disk('public')->delete($old->file_path);$old->delete();}return back()->with('success','Berita acara berhasil diunggah.');}
 public function destroyEvent(CertificationEvent $event){
  $this->guard();$event->load('participants');$folderIds=collect();if($event->folder_id){$folderIds->push($event->folder_id);do{$children=Folder::whereIn('parent_id',$folderIds)->whereNotIn('id',$folderIds)->pluck('id');if($children->isNotEmpty())$folderIds=$folderIds->merge($children)->unique()->values();}while($children->isNotEmpty());}
  $linkedFileIds=$event->participants->pluck('biodata_file_id')->push($event->minutes_file_id)->filter()->unique();$documentFiles=($folderIds->isEmpty()&&$linkedFileIds->isEmpty())?collect():File::where(function($query)use($folderIds,$linkedFileIds){if($folderIds->isNotEmpty())$query->whereIn('folder_id',$folderIds);if($linkedFileIds->isNotEmpty())$query->orWhereIn('id',$linkedFileIds);})->get();$documentPaths=$documentFiles->pluck('file_path');$signaturePaths=$event->participants->pluck('signature_path')->filter();$title=$event->title;
  DB::transaction(function()use($event,$folderIds,$documentFiles){$event->delete();if($folderIds->isNotEmpty())Folder::whereKey($folderIds->first())->delete();if($documentFiles->isNotEmpty())File::whereIn('id',$documentFiles->pluck('id'))->delete();});
  Storage::disk('public')->delete($documentPaths->merge($signaturePaths)->filter()->unique()->values()->all());
  return redirect()->route('certifications.index')->with('success','Pelaksanaan '.$title.' beserta seluruh peserta, folder, dan dokumennya berhasil dihapus.');
 }
 public function export(Request $r){$this->guard();$d=$r->validate(['year'=>'required|integer|min:2000|max:'.(now()->year+1)]);$year=(int)$d['year'];abort_unless(CertificationEvent::whereYear('start_date',$year)->exists(),422,'Tidak ada pelaksanaan sertifikasi pada tahun yang dipilih.');return Excel::download(new CertificationYearExport($year),'rekap-sertifikasi-'.$year.'.xlsx');}
 public function template(){ $this->guard();$rows=[['nip_nik','nama','jenis_kelamin','jabatan','instansi','provinsi','kabupaten_kota','nomor_hp','email'],["'320000000000000001",'Contoh Peserta','Laki-laki','Analis','Pemerintah Kabupaten/Kota','Jawa Barat','Kota Bandung','081234567890','peserta@example.go.id']];return Excel::download(new class($rows) implements FromArray{public function __construct(private array $rows){}public function array():array{return $this->rows;}},'template_peserta_sertifikasi.xlsx');}
 private function createFolders(string $title):array{$base=['bidang'=>self::BIDANG,'user_id'=>Auth::id(),'is_public'=>false];$cert=Folder::firstOrCreate(['name'=>'Sertifikasi','parent_id'=>null,'bidang'=>self::BIDANG],$base);$event=Folder::create($base+['name'=>$title,'parent_id'=>$cert->id]);Folder::create($base+['name'=>'Berita Acara','parent_id'=>$event->id]);Folder::create($base+['name'=>'Data Peserta','parent_id'=>$event->id]);return compact('event');}
 private function childFolder(CertificationEvent $event,string $name):Folder{return Folder::firstOrCreate(['name'=>$name,'parent_id'=>$event->folder_id,'bidang'=>self::BIDANG],['user_id'=>Auth::id(),'is_public'=>false]);}
 private function storeDocument($upload,Folder $folder):File{$path=$upload->store('documents','public');return File::create(['folder_id'=>$folder->id,'display_name'=>$upload->getClientOriginalName(),'file_path'=>$path,'file_type'=>$upload->getClientOriginalExtension(),'file_size'=>$upload->getSize(),'user_id'=>Auth::id()]);}
}
