<?php
namespace App\Http\Controllers;
use App\Models\DailyReport;
use App\Models\DailyReportAssignment;
use App\Models\EmploymentStatus;
use App\Models\Institution;
use App\Models\User;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use PhpOffice\PhpSpreadsheet\IOFactory;
class DailyReportManagementController extends Controller {
 private function allowed(){abort_unless(in_array(auth()->user()->role,['superadmin','kasubag_pppk_pw'],true),403);}
 public function index(Request $r){$this->allowed();$q=DailyReportAssignment::with(['user','supervisor','institution'])->withCount('reports');if(auth()->user()->role==='kasubag_pppk_pw')$q->where('supervisor_user_id',auth()->id());$assignments=$q->latest()->paginate(15);$supervisors=User::where('role','kasubag_pppk_pw')->orderBy('name')->get();$institution=Institution::where('is_internal_bpsdm',true)->first();return view('daily-report-management.index',compact('assignments','supervisors','institution'));}
 public function storeAssignment(Request $r){abort_unless(auth()->user()->role==='superadmin',403);$d=$r->validate(['employee_email'=>'required|email','supervisor_user_id'=>'required|exists:users,id','start_date'=>'required|date','end_date'=>'nullable|date|after_or_equal:start_date']);$institution=Institution::where('is_internal_bpsdm',true)->firstOrFail();$user=User::whereRaw('LOWER(username)=?',[strtolower($d['employee_email'])])->first();$status=EmploymentStatus::where('code','PPPK-PW')->first();if($user)$user->update(['institution_id'=>$institution->id,'instansi'=>$institution->name,'employment_status_id'=>$status?->id,'status_kepegawaian'=>$status?->name?:'PPPK-PW']);DailyReportAssignment::updateOrCreate(['employee_email'=>strtolower($d['employee_email'])],$d+['employee_email'=>strtolower($d['employee_email']),'user_id'=>$user?->id,'institution_id'=>$institution->id,'is_active'=>true,'created_by'=>auth()->id()]);return back()->with('success',$user?'Pegawai ditugaskan dan akun berhasil dihubungkan.':'Penugasan disimpan. Akun akan terhubung otomatis saat login Google.');}
 public function template(){abort_unless(auth()->user()->role==='superadmin',403);$rows=[['Email Google Pegawai','Email/Username Kasubag','Tanggal Mulai','Tanggal Selesai','Status Aktif'],['pegawai@gmail.com','kasubag@jabarprov.go.id',now()->format('Y-m-d'),now()->addYear()->format('Y-m-d'),'Ya']];return Excel::download(new class($rows)implements \Maatwebsite\Excel\Concerns\FromArray,\Maatwebsite\Excel\Concerns\ShouldAutoSize,\Maatwebsite\Excel\Concerns\WithStyles{public function __construct(private array $rows){}public function array():array{return $this->rows;}public function styles(\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet $sheet):array{$sheet->freezePane('A2');return[1=>['font'=>['bold'=>true,'color'=>['argb'=>'FFFFFFFF']],'fill'=>['fillType'=>'solid','startColor'=>['argb'=>'FF284B9B']]]];}},'template-import-pegawai-pppk-pw.xlsx');}
 public function import(Request $r){abort_unless(auth()->user()->role==='superadmin',403);$r->validate(['file'=>'required|file|mimes:xlsx,xls|max:10240']);$institution=Institution::where('is_internal_bpsdm',true)->firstOrFail();$employmentStatus=EmploymentStatus::where('code','PPPK-PW')->first();$rows=collect(IOFactory::load($r->file('file')->getRealPath())->getActiveSheet()->toArray());$header=$rows->shift();if(!$header)return back()->with('error','File tidak memiliki header. Gunakan template resmi.');$keys=collect($header)->map(fn($v)=>\Illuminate\Support\Str::slug((string)$v,'_'))->all();$created=0;$updated=0;$linked=0;$skipped=[];foreach($rows as $index=>$row){$data=array_combine($keys,array_pad(array_values($row),count($keys),null));$email=strtolower(trim((string)($data['email_google_pegawai']??'')));$supervisorLogin=trim((string)($data['email_username_kasubag']??''));$start=$this->excelDate($data['tanggal_mulai']??null);$end=$this->excelDate($data['tanggal_selesai']??null);if(!filter_var($email,FILTER_VALIDATE_EMAIL)||$supervisorLogin===''||!$start){$skipped[]='baris '.($index+2).' (data wajib tidak valid)';continue;}$supervisor=User::where('role','kasubag_pppk_pw')->where(fn($q)=>$q->whereRaw('LOWER(username)=?',[strtolower($supervisorLogin)])->orWhere('nip_nik',$supervisorLogin))->first();if(!$supervisor){$skipped[]='baris '.($index+2).' (Kasubag tidak ditemukan)';continue;}if($end&&$end<$start){$skipped[]='baris '.($index+2).' (tanggal selesai sebelum mulai)';continue;}$user=User::whereRaw('LOWER(username)=?',[$email])->first();if($user){$user->update(['institution_id'=>$institution->id,'instansi'=>$institution->name,'employment_status_id'=>$employmentStatus?->id,'status_kepegawaian'=>$employmentStatus?->name?:'PPPK-PW']);$linked++;}$existing=DailyReportAssignment::where('employee_email',$email)->first();DailyReportAssignment::updateOrCreate(['employee_email'=>$email],['user_id'=>$user?->id,'supervisor_user_id'=>$supervisor->id,'institution_id'=>$institution->id,'start_date'=>$start,'end_date'=>$end,'is_active'=>$this->truthy($data['status_aktif']??'Ya'),'created_by'=>auth()->id()]);$existing?$updated++:$created++;}return back()->with('success',"Import selesai: {$created} ditambahkan, {$updated} diperbarui, {$linked} akun langsung terhubung".($skipped?'; '.count($skipped).' dilewati: '.implode(', ',$skipped):'').'.');}
 public function reports(Request $r){$this->allowed();$q=DailyReport::with(['assignment.user','items']);if(auth()->user()->role==='kasubag_pppk_pw')$q->whereHas('assignment',fn($x)=>$x->where('supervisor_user_id',auth()->id()));$q->when($r->month,fn($x)=>$x->whereYear('report_date',substr($r->month,0,4))->whereMonth('report_date',substr($r->month,5,2)));$reports=$q->latest('report_date')->paginate(20)->withQueryString();return view('daily-report-management.reports',compact('reports'));}
 private function truthy($value):bool{return in_array(strtolower(trim((string)$value)),['ya','y','1','aktif','true'],true);}
 private function excelDate($value):?string{if(blank($value))return null;try{if(is_numeric($value))return \PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject($value)->format('Y-m-d');return \Carbon\Carbon::parse($value)->format('Y-m-d');}catch(\Throwable){return null;}}
}
