<?php
namespace App\Http\Controllers;
use App\Models\InternshipAttendance;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
class InternshipDashboardController extends Controller {
 private function participant(){abort_unless(Auth::user()->role==='intern',403);return Auth::user()->internshipParticipant()->with('program')->firstOrFail();}
 private function now():Carbon{return now('Asia/Jakarta');}
 private function ensureActive($participant):void {$today=$this->now()->toDateString();if($participant->status!=='approved'||$today<$participant->start_date->toDateString()||$today>$participant->end_date->toDateString())throw ValidationException::withMessages(['attendance'=>'Presensi hanya tersedia selama periode magang aktif.']);}
 public function index(){ $participant=$this->participant();$attendances=$participant->attendances()->latest('attendance_date')->take(14)->get();$todayAttendance=$participant->attendances()->whereDate('attendance_date',$this->now()->toDateString())->first();$stats=['present'=>$participant->attendances()->whereIn('status',['present','permission','sick'])->count(),'late_days'=>$participant->attendances()->where('late_minutes','>',0)->count(),'late_minutes'=>(int)$participant->attendances()->sum('late_minutes'),'permission'=>$participant->attendances()->where('status','permission')->count(),'sick'=>$participant->attendances()->where('status','sick')->count()];$now=$this->now();$canCheckIn=$now->format('H:i')>=substr($participant->program->check_in_opens_at,0,5)&&!$todayAttendance;$canCheckOut=$now->format('H:i')>=substr($participant->program->check_out_opens_at,0,5)&&$todayAttendance?->status==='present'&&!$todayAttendance?->check_out_at;$internshipEnded=$now->toDateString()>$participant->end_date->toDateString();$certificateAvailable=$internshipEnded&&$participant->certificate_sent_at&&$participant->certificate_file_path&&Storage::disk('local')->exists($participant->certificate_file_path);return view('internships.dashboard',compact('participant','stats','attendances','todayAttendance','canCheckIn','canCheckOut','now','internshipEnded','certificateAvailable')); }
 public function downloadCertificate(){ $participant=$this->participant();abort_unless($this->now()->toDateString()>$participant->end_date->toDateString(),403,'Sertifikat tersedia setelah masa magang selesai.');abort_unless($participant->certificate_sent_at,403,'Sertifikat belum dikirim oleh pengelola.');abort_unless($participant->certificate_file_path&&Storage::disk('local')->exists($participant->certificate_file_path),404,'Sertifikat belum diterbitkan.');$participant->update(['certificate_downloaded_at'=>now()]);return Storage::disk('local')->download($participant->certificate_file_path,Str::slug($participant->name.'-'.$participant->student_number).'-sertifikat-magang.pdf');}
 public function checkIn(Request $request){$participant=$this->participant();$this->ensureActive($participant);$request->validate(['selfie'=>'required|image|mimes:jpg,jpeg,png,webp|max:5120'],['selfie.required'=>'Selfie presensi masuk wajib diambil.','selfie.max'=>'Ukuran selfie maksimal 5 MB.']);$now=$this->now();$open=Carbon::parse($now->toDateString().' '.$participant->program->check_in_opens_at,'Asia/Jakarta');if($now->lt($open))throw ValidationException::withMessages(['attendance'=>'Presensi masuk baru dibuka pukul '.$open->format('H:i').' WIB.']);if($participant->attendances()->whereDate('attendance_date',$now->toDateString())->exists())throw ValidationException::withMessages(['attendance'=>'Status presensi hari ini sudah tercatat.']);$late=Carbon::parse($now->toDateString().' '.$participant->program->late_after,'Asia/Jakarta');$minutes=$now->gt($late)?$late->diffInMinutes($now):0;$path=$request->file('selfie')->store('internships/attendance/'.$participant->id.'/'.$now->toDateString(),'local');try{$participant->attendances()->create(['attendance_date'=>$now->toDateString(),'status'=>'present','check_in_at'=>$now,'late_minutes'=>$minutes,'check_in_photo_path'=>$path]);}catch(\Throwable $e){Storage::disk('local')->delete($path);throw $e;}return back()->with('success',$minutes?'Presensi masuk tercatat. Anda terlambat '.$minutes.' menit.':'Presensi masuk tepat waktu berhasil tercatat.');}
 public function checkOut(Request $request){$participant=$this->participant();$this->ensureActive($participant);$request->validate(['selfie'=>'required|image|mimes:jpg,jpeg,png,webp|max:5120'],['selfie.required'=>'Selfie presensi pulang wajib diambil.','selfie.max'=>'Ukuran selfie maksimal 5 MB.']);$now=$this->now();$open=Carbon::parse($now->toDateString().' '.$participant->program->check_out_opens_at,'Asia/Jakarta');if($now->lt($open))throw ValidationException::withMessages(['attendance'=>'Presensi pulang baru dibuka pukul '.$open->format('H:i').' WIB.']);$attendance=$participant->attendances()->whereDate('attendance_date',$now->toDateString())->where('status','present')->first();if(!$attendance||$attendance->check_out_at)throw ValidationException::withMessages(['attendance'=>'Presensi masuk belum ada atau presensi pulang sudah tercatat.']);$path=$request->file('selfie')->store('internships/attendance/'.$participant->id.'/'.$now->toDateString(),'local');$attendance->update(['check_out_at'=>$now,'check_out_photo_path'=>$path]);return back()->with('success','Presensi pulang berhasil tercatat.');}
 public function absence(Request $request){$participant=$this->participant();$this->ensureActive($participant);$data=$request->validate(['type'=>'required|in:permission,sick','note'=>'required|string|min:10|max:2000','evidence'=>'nullable|file|mimes:pdf,jpg,jpeg,png|max:5120']);if($data['type']==='sick'&&!$request->hasFile('evidence'))throw ValidationException::withMessages(['evidence'=>'Bukti sakit wajib diunggah.']);$date=$this->now()->toDateString();if($participant->attendances()->whereDate('attendance_date',$date)->exists())throw ValidationException::withMessages(['attendance'=>'Status presensi hari ini sudah tercatat.']);$path=$request->hasFile('evidence')?$request->file('evidence')->store('internships/evidence/'.$participant->id,'local'):null;$participant->attendances()->create(['attendance_date'=>$date,'status'=>$data['type'],'note'=>$data['note'],'evidence_path'=>$path,'review_status'=>'not_required']);return back()->with('success','Catatan '.($data['type']==='sick'?'sakit':'izin').' berhasil disimpan. Presensi hari ini ditutup.');}
}