@extends('layouts.master')
@section('title',$report?'Edit Laporan':'Buat Laporan')
@section('content')
<div class="container-xxl container-p-y"><a href="{{route('daily-reports.index')}}" class="btn btn-sm btn-outline-secondary mb-3"><i class="bx bx-left-arrow-alt"></i> Kembali</a>@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{$e}}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{route('daily-reports.store')}}" class="card border-0 shadow-sm">@csrf<div class="card-header border-bottom"><h4 class="fw-bold mb-1">{{$report?'Edit':'Buat'}} Laporan Harian</h4><small class="text-muted">Pilih tanggal kerja, lalu tuliskan kegiatan beserta hasil atau kesimpulannya.</small></div><div class="card-body"><div class="report-date-panel mb-4"><div class="d-flex align-items-center gap-3"><span class="date-icon"><i class="bx bx-calendar"></i></span><div class="flex-grow-1"><label class="form-label fw-bold mb-1">Tanggal Laporan</label><button type="button" id="calendarTrigger" class="date-trigger"><span id="selectedDateLabel">Pilih tanggal laporan</span><i class="bx bx-chevron-down"></i></button><input type="hidden" id="reportDate" name="report_date" value="{{old('report_date',$report?->report_date?->format('Y-m-d')?:today()->format('Y-m-d'))}}" required></div></div><div id="calendarPanel" class="calendar-panel d-none"><div class="calendar-head"><button type="button" id="prevMonth" class="calendar-nav"><i class="bx bx-chevron-left"></i></button><strong id="calendarTitle"></strong><button type="button" id="nextMonth" class="calendar-nav"><i class="bx bx-chevron-right"></i></button></div><div class="calendar-week"><span>Sen</span><span>Sel</span><span>Rab</span><span>Kam</span><span>Jum</span><span>Sab</span><span>Min</span></div><div id="calendarDays" class="calendar-days"></div></div><small class="text-muted d-block mt-2">Tanggal tersedia sesuai periode penugasan sampai hari ini.</small></div><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="fw-bold mb-1">Rincian Kegiatan</h5><small class="text-muted">Anda dapat menambahkan lebih dari satu kegiatan dalam satu hari.</small></div><button type="button" id="addItem" class="btn btn-sm btn-outline-primary"><i class="bx bx-plus"></i> Tambah Kegiatan</button></div><div id="items"></div></div><div class="card-footer d-flex justify-content-end"><button type="submit" class="btn btn-primary"><i class="bx bx-save me-1"></i> Simpan Laporan</button></div></form></div>
<template id="itemTemplate"><div class="activity-item rounded-3 p-3 mb-3 position-relative"><button type="button" class="remove-item btn btn-sm btn-icon btn-outline-danger position-absolute top-0 end-0 m-2" title="Hapus kegiatan"><i class="bx bx-trash"></i></button><div class="row g-3 pe-md-4"><div class="col-md-2"><label class="form-label fw-semibold">Jam Mulai</label><input type="time" data-field="start_time" class="form-control" required></div><div class="col-md-2"><label class="form-label fw-semibold">Jam Selesai</label><input type="time" data-field="end_time" class="form-control" required></div><div class="col-md-8"><label class="form-label fw-semibold">Kegiatan</label><textarea data-field="activity" class="form-control" rows="2" placeholder="Tuliskan kegiatan yang dilaksanakan" required></textarea></div><div class="col-12"><label class="form-label fw-semibold">Hasil / Output / Kesimpulan Kegiatan</label><textarea data-field="output" class="form-control" rows="3" placeholder="Tuliskan hasil pekerjaan, output, atau kesimpulan kegiatan" required></textarea></div></div></div></template>
@endsection
@push('js')
@php
    $defaultItems = [['start_time' => '08:00', 'end_time' => '09:00', 'activity' => '', 'output' => '']];
    $existingItems = old('items', $report ? $report->items->toArray() : $defaultItems);
@endphp
<script>
const existing={{ Illuminate\Support\Js::from($existingItems) }};const box=document.getElementById('items'),tpl=document.getElementById('itemTemplate');function add(data={}){const node=tpl.content.firstElementChild.cloneNode(true);box.appendChild(node);Object.entries(data).forEach(([k,v])=>{const el=node.querySelector(`[data-field="${k}"]`);if(el)el.value=['start_time','end_time'].includes(k)?String(v??'').slice(0,5):String(v??'')});renumber();node.querySelector('.remove-item').onclick=()=>{node.remove();if(!box.children.length)add();renumber()}}function renumber(){[...box.children].forEach((node,i)=>node.querySelectorAll('[data-field]').forEach(el=>el.name=`items[${i}][${el.dataset.field}]`))}existing.forEach(add);document.getElementById('addItem').onclick=()=>add();
const input=document.getElementById('reportDate'),panel=document.getElementById('calendarPanel'),label=document.getElementById('selectedDateLabel'),title=document.getElementById('calendarTitle'),days=document.getElementById('calendarDays');const minDate='{{$a->start_date->format('Y-m-d')}}',maxDate='{{min($a->end_date?->format('Y-m-d')?:today()->format('Y-m-d'),today()->format('Y-m-d'))}}';let cursor=new Date((input.value||maxDate)+'T12:00:00');const monthNames=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];function formatLabel(value){const d=new Date(value+'T12:00:00');return d.toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}function refreshLabel(){label.textContent=input.value?formatLabel(input.value):'Pilih tanggal laporan'}function renderCalendar(){title.textContent=`${monthNames[cursor.getMonth()]} ${cursor.getFullYear()}`;days.innerHTML='';const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),offset=(first.getDay()+6)%7,total=new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate();for(let i=0;i<offset;i++)days.insertAdjacentHTML('beforeend','<span></span>');for(let day=1;day<=total;day++){const value=`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,button=document.createElement('button');button.type='button';button.textContent=day;button.className='calendar-day';if(value<input.value&&false){}if(value<minDate||value>maxDate){button.disabled=true}else{button.onclick=()=>{input.value=value;refreshLabel();renderCalendar();panel.classList.add('d-none')}}if(value===input.value)button.classList.add('selected');if(value==='{{today()->format('Y-m-d')}}')button.classList.add('today');days.appendChild(button)}}document.getElementById('calendarTrigger').onclick=()=>{panel.classList.toggle('d-none');renderCalendar()};document.getElementById('prevMonth').onclick=()=>{cursor.setMonth(cursor.getMonth()-1);renderCalendar()};document.getElementById('nextMonth').onclick=()=>{cursor.setMonth(cursor.getMonth()+1);renderCalendar()};document.addEventListener('click',e=>{if(!e.target.closest('.report-date-panel'))panel.classList.add('d-none')});refreshLabel();renderCalendar();
</script>
@endpush

@push('css')
<style>.report-date-panel{position:relative;padding:18px;border:1px solid #dbe5f5;border-radius:16px;background:linear-gradient(135deg,#f8fbff,#f0f6ff)}.date-icon{width:48px;height:48px;border-radius:14px;display:grid;place-items:center;background:#4169e1;color:#fff;font-size:25px}.date-trigger{width:100%;display:flex;justify-content:space-between;align-items:center;border:0;background:transparent;padding:3px 0;color:#22304a;font-size:16px;text-align:left}.calendar-panel{position:absolute;z-index:20;top:92px;left:76px;width:min(340px,calc(100% - 92px));padding:16px;border:1px solid #dce4f0;border-radius:16px;background:#fff;box-shadow:0 18px 45px rgba(32,55,95,.18)}.calendar-head,.calendar-week,.calendar-days{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.calendar-head{grid-template-columns:38px 1fr 38px;align-items:center;margin-bottom:12px;text-align:center}.calendar-nav{border:0;background:#eef3ff;color:#3159bd;border-radius:10px;height:34px}.calendar-week span{text-align:center;color:#8390a5;font-size:11px;font-weight:700;padding:4px}.calendar-day{aspect-ratio:1;border:0;border-radius:10px;background:transparent;color:#344258}.calendar-day:hover:not(:disabled){background:#eaf0ff;color:#3159bd}.calendar-day.selected{background:#4169e1!important;color:#fff!important}.calendar-day.today{box-shadow:inset 0 0 0 1px #4169e1}.calendar-day:disabled{color:#ccd1da;cursor:not-allowed}.activity-item{border:1px solid #e1e7f0;background:#fbfcff}@media(max-width:576px){.calendar-panel{left:12px;top:100px;width:calc(100% - 24px)}}</style>
@endpush
