@extends('layouts.master')
@section('title','Laporan Harian')
@section('content')
<div class="container-xxl container-p-y"><div class="report-hero mb-4"><div><small>PPPK-PW INTERNAL BPSDM</small><h3 class="text-white fw-bold mb-1">Laporan Harian Saya</h3><p class="text-white-50 mb-0">{{$a->user->name}}  Dipantau {{$a->supervisor->name}}</p></div><a href="{{route('daily-reports.create')}}" class="btn btn-light text-primary"><i class="bx bx-plus"></i> Buat Laporan</a></div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
@if(session('error'))<div class="alert alert-danger">{{session('error')}}</div>@endif
<div class="card border-0 shadow-sm"><div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-3"><div><h5 class="mb-0">Riwayat Laporan Bulanan</h5><small class="text-muted">Periode penugasan {{$a->start_date->translatedFormat('d M Y')}} s.d. {{$a->end_date?->translatedFormat('d M Y')?:'seterusnya'}}</small></div><div class="d-flex flex-wrap gap-2"><form class="d-flex gap-2"><input type="month" name="month" value="{{$month}}" class="form-control"><button class="btn btn-outline-primary" type="submit"><i class="bx bx-filter-alt"></i> Tampilkan</button></form><a href="{{route('daily-reports.monthly-pdf',['month'=>$month])}}" class="btn btn-danger"><i class="bx bxs-file-pdf me-1"></i> Unduh PDF Bulanan</a></div></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Tanggal</th><th>Rincian</th><th>Status</th><th></th></tr></thead><tbody>@forelse($reports as $report)<tr><td><strong>{{$report->report_date->translatedFormat('l, d M Y')}}</strong></td><td>{{$report->items_count}} kegiatan</td><td><span class="badge bg-label-success">Tersimpan</span></td><td class="text-end"><a href="{{route('daily-reports.show',$report)}}" class="btn btn-sm btn-outline-primary" title="Lihat"><i class="bx bx-show"></i></a><a href="{{route('daily-reports.edit',$report)}}" class="btn btn-sm btn-outline-warning" title="Edit"><i class="bx bx-edit"></i></a></td></tr>@empty<tr><td colspan="4" class="text-center py-5"><i class="bx bx-notepad fs-1 text-muted"></i><p class="mt-2 mb-0">Belum ada laporan pada bulan ini.</p></td></tr>@endforelse</tbody></table></div>@if($reports->hasPages())<div class="card-footer">{{$reports->links()}}</div>@endif</div></div>
@endsection
@push('css')<style>.report-hero{display:flex;justify-content:space-between;align-items:center;gap:2rem;padding:2rem;border-radius:20px;background:linear-gradient(120deg,#274894,#647fee);box-shadow:0 14px 30px rgba(39,72,148,.2)}@media(max-width:600px){.report-hero{align-items:flex-start;flex-direction:column}}</style>@endpush
