@extends('certifications.public_layout')
@section('title','Evaluasi dan Unggah Sertifikat')
@section('public_subtitle','Evaluasi dan Pengumpulan Sertifikat')
@section('content')
@php $ratingLabels=[1=>'Sangat Kurang',2=>'Kurang',3=>'Cukup',4=>'Baik',5=>'Sangat Baik']; @endphp
<div class="card border-0 shadow-lg"><div class="card-header bg-success text-white p-4"><span class="badge bg-white text-success mb-2">PESERTA LULUS</span><h4 class="text-white fw-bold mb-1">Evaluasi & Pengumpulan Sertifikat</h4><p class="mb-0 opacity-75">{{ $event->title }}</p></div><div class="card-body p-4 p-md-5">
@if(session('success'))<div class="alert alert-success"><i class="bx bx-check-circle me-1"></i>{{ session('success') }}@if($participant->certificateFile)<div class="mt-2"><a href="{{ route('documents.file.download',$participant->certificateFile) }}" class="btn btn-sm btn-success"><i class="bx bx-download me-1"></i>Download Sertifikat</a></div>@endif</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Form belum dapat disimpan.</strong><div>{{ $errors->first() }}</div></div>@endif
@if($participant->certificate_submitted_at)<div class="alert alert-info"><i class="bx bx-info-circle me-1"></i>Terakhir dikirim {{ $participant->certificate_submitted_at->translatedFormat('d M Y, H:i') }}. Data dapat diperbarui kembali.</div>@endif
<form method="POST" enctype="multipart/form-data" action="{{ route('certifications.certificates.public.submit',[$event->public_token,$participant->biodata_token]) }}">@csrf<div class="row g-4">
 <div class="col-12"><label class="form-label">Nama Lengkap Peserta</label><div class="form-control bg-light fw-semibold">{{ $participant->name }}</div><div class="form-text">Nama otomatis berdasarkan NIP/NIK yang dimasukkan.</div></div>
 <div class="col-md-6"><label class="form-label required">Nomor Sertifikat</label><input name="certificate_number" value="{{ old('certificate_number',$participant->certificate_number) }}" class="form-control" required></div>
 <div class="col-md-6"><label class="form-label {{ $participant->certificate_file_id?'':'required' }}">Unggah File Sertifikat</label><input type="file" name="certificate_file" accept="application/pdf,.pdf" class="form-control" {{ $participant->certificate_file_id?'':'required' }}><div class="form-text">PDF maksimal 20 MB. Kosongkan jika tidak ingin mengganti file sebelumnya.</div></div>
 <div class="col-12"><hr><label class="form-label required">Bagaimana penilaian Anda terhadap pelaksanaan sertifikasi?</label><div class="rating-scale"><input type="range" name="certification_rating" id="ratingInput" min="1" max="5" step="1" value="{{ old('certification_rating',$participant->certification_rating?:5) }}" class="form-range"><div class="d-flex justify-content-between small text-muted">@foreach($ratingLabels as $number=>$label)<span class="text-center"><strong>{{ $number }}</strong><small class="d-none d-md-block">{{ $label }}</small></span>@endforeach</div><div class="rating-result mt-3"><span id="ratingNumber">5</span><div><strong id="ratingLabel">Sangat Baik</strong><small>Penilaian Anda</small></div></div></div></div>
 <div class="col-12"><label class="form-label">Saran atau Kendala Selama Mengikuti Sertifikasi</label><textarea name="certification_feedback" class="form-control" rows="5" placeholder="Tuliskan saran atau kendala jika ada...">{{ old('certification_feedback',$participant->certification_feedback) }}</textarea><div class="form-text">Jawaban paragraf—boleh tidak diisi.</div></div>
</div><div class="alert alert-warning mt-4 small"><i class="bx bx-folder me-1"></i>File akan disimpan pada folder kegiatan sertifikasi / Sertifikat Peserta menggunakan nama peserta.</div><button class="btn btn-success btn-lg w-100"><i class="bx bx-cloud-upload me-1"></i>Simpan Evaluasi dan Sertifikat</button></form>
</div></div>
@endsection
@push('css')<style>.rating-scale{padding:1.25rem;border:1px solid #e5e7eb;border-radius:12px;background:#f8fafc}.rating-result{display:flex;align-items:center;justify-content:center;gap:.8rem}.rating-result>span{display:grid;place-items:center;width:52px;height:52px;border-radius:50%;background:#71dd37;color:#fff;font-size:1.5rem;font-weight:700}.rating-result strong,.rating-result small{display:block}.rating-result small{color:#8592a3}</style>@endpush
@push('js')<script>(()=>{const input=document.getElementById('ratingInput'),number=document.getElementById('ratingNumber'),label=document.getElementById('ratingLabel'),labels={1:'Sangat Kurang',2:'Kurang',3:'Cukup',4:'Baik',5:'Sangat Baik'};function update(){number.textContent=input.value;label.textContent=labels[input.value]}input.addEventListener('input',update);update()})();</script>@endpush
