@extends('certifications.public_layout')
@section('title','Form Biodata Sertifikasi')
@section('content')
<div class="card border-0 shadow-lg"><div class="card-header bg-primary text-white p-4"><h4 class="text-white fw-bold mb-1">Biodata Peserta</h4><p class="mb-0 opacity-75">{{$event->title}}</p></div><div class="card-body p-4 p-md-5">
@if(session('success'))<div class="alert alert-success"><i class="bx bx-check-circle me-1"></i>{{session('success')}}@if($participant->biodataFile)<div class="mt-2"><a href="{{route('documents.file.download',$participant->biodataFile)}}" class="btn btn-sm btn-success"><i class="bx bx-download me-1"></i>Download PDF Biodata</a></div>@endif</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Form belum dapat disimpan.</strong><div>{{$errors->first()}}</div></div>@endif
@if($participant->biodata_submitted_at)<div class="alert alert-info"><i class="bx bx-info-circle me-1"></i>Biodata terakhir diperbarui {{$participant->biodata_submitted_at->translatedFormat('d M Y, H:i')}}. Anda dapat memperbaruinya kembali.</div>@endif
<form method="POST" action="{{route('certifications.public.submit',[$event->public_token,$participant->biodata_token])}}" id="biodataForm">@csrf<div class="row g-3">
 <div class="col-md-8"><label class="form-label required">Nama Lengkap dengan Gelar</label><input name="name" class="form-control" value="{{old('name',$participant->name)}}" required></div><div class="col-md-4"><label class="form-label required">NIP/NIK</label><input name="nip_nik" class="form-control" value="{{old('nip_nik',$participant->nip_nik)}}" required></div>
 <div class="col-md-6"><label class="form-label required">Tempat/Tanggal Lahir</label><input name="birth_place_date" class="form-control" value="{{old('birth_place_date',$participant->birth_place_date)}}" placeholder="Contoh: Bandung, 17 Agustus 1990" required></div><div class="col-md-6"><label class="form-label">Pangkat/Golongan</label><input name="rank_grade" class="form-control" value="{{old('rank_grade',$participant->rank_grade)}}"></div>
 <div class="col-md-6"><label class="form-label required">Jabatan</label><input name="position" class="form-control" value="{{old('position',$participant->position)}}" required></div><div class="col-md-6"><label class="form-label required">Instansi</label><input name="institution" class="form-control" value="{{old('institution',$participant->institution)}}" required></div>
 <div class="col-md-4"><label class="form-label required">Agama</label><select name="religion" class="form-select" required><option value="">Pilih</option>@foreach(['Islam','Kristen','Katolik','Hindu','Buddha','Konghucu','Lainnya'] as $v)<option value="{{$v}}" @selected(old('religion',$participant->religion)===$v)>{{$v}}</option>@endforeach</select></div>
 <div class="col-md-4"><label class="form-label required">Jenis Kelamin</label><select name="gender" class="form-select" required><option value="">Pilih</option>@foreach(['Laki-laki','Perempuan'] as $v)<option value="{{$v}}" @selected(old('gender',$participant->gender)===$v)>{{$v}}</option>@endforeach</select></div>
 <div class="col-md-4"><label class="form-label required">Pendidikan Terakhir/Tahun</label><input name="education" class="form-control" value="{{old('education',$participant->education)}}" placeholder="S1 / 2018" required></div>
 <div class="col-12"><label class="form-label required">Alamat Kantor dan Telepon</label><textarea name="office_address" class="form-control" rows="3" required>{{old('office_address',$participant->office_address)}}</textarea></div>
 <div class="col-md-6"><label class="form-label required">Nomor HP/WhatsApp</label><input name="phone" class="form-control" value="{{old('phone',$participant->phone)}}" required></div><div class="col-md-6"><label class="form-label required">Email</label><input type="email" name="email" class="form-control" value="{{old('email',$participant->email)}}" required></div>
 <div class="col-12"><label class="form-label">Diklat yang Pernah Diikuti</label><textarea name="trainings" class="form-control" rows="4" placeholder="Tuliskan nama diklat dan tahun, satu baris untuk setiap diklat.">{{old('trainings',$participant->trainings)}}</textarea></div>
 <div class="col-12 mt-4"><div class="d-flex justify-content-between align-items-center mb-2"><label class="form-label required mb-0">Tanda Tangan</label><button type="button" class="btn btn-sm btn-outline-danger" id="clearSignature"><i class="bx bx-eraser me-1"></i>Hapus/Ulangi</button></div><div class="signature-wrap"><canvas id="signatureCanvas" class="signature-canvas"></canvas><div class="signature-line"></div><div class="signature-hint">Tanda tangan di dalam kotak menggunakan jari, stylus, atau mouse</div><div style="height:18px"></div></div><input type="hidden" name="signature_data" id="signatureData"><div id="signatureError" class="text-danger small mt-1 d-none">Silakan bubuhkan tanda tangan terlebih dahulu.</div></div>
 </div><div class="alert alert-warning mt-4 small"><i class="bx bx-file me-1"></i>Dengan mengirim formulir, sistem akan membuat PDF biodata resmi berdasarkan template BPSDM.</div><button class="btn btn-primary btn-lg w-100" id="submitButton"><i class="bx bx-save me-1"></i>Simpan dan Buat PDF</button></form>
</div></div>
@endsection
@push('js')<script>
(()=>{const canvas=document.getElementById('signatureCanvas'),ctx=canvas.getContext('2d'),hidden=document.getElementById('signatureData'),form=document.getElementById('biodataForm'),error=document.getElementById('signatureError');let drawing=false,signed={{$participant->signature_path?'true':'false'}},signatureChanged=false;
function setup(){const rect=canvas.getBoundingClientRect(),ratio=Math.max(window.devicePixelRatio||1,1);canvas.width=rect.width*ratio;canvas.height=210*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.lineWidth=2.2;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#1f2937';@if($participant->signature_path)const img=new Image();img.onload=()=>ctx.drawImage(img,20,20,rect.width-40,150);img.src="{{asset('storage/'.$participant->signature_path)}}";@endif}
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}canvas.addEventListener('pointerdown',e=>{e.preventDefault();drawing=true;canvas.setPointerCapture(e.pointerId);const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y)});canvas.addEventListener('pointermove',e=>{if(!drawing)return;e.preventDefault();const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();signed=true;signatureChanged=true;error.classList.add('d-none')});['pointerup','pointercancel','pointerleave'].forEach(n=>canvas.addEventListener(n,()=>drawing=false));document.getElementById('clearSignature').onclick=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);signed=false;signatureChanged=true;hidden.value=''};
form.addEventListener('submit',e=>{if(!signed){e.preventDefault();error.classList.remove('d-none');canvas.scrollIntoView({behavior:'smooth',block:'center'});return}if(signatureChanged&&canvas.toDataURL)hidden.value=canvas.toDataURL('image/png');const btn=document.getElementById('submitButton');btn.disabled=true;btn.innerHTML='<span class="spinner-border spinner-border-sm me-1"></span>Membuat PDF...'});setup()})();
</script>@endpush
