@extends('layouts.master')
@section('title','Kelola Pelaksanaan Sertifikasi')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><a href="{{route('certifications.index')}}" class="small"><i class="bx bx-arrow-back"></i> Kembali</a><h4 class="fw-bold mt-2 mb-1">{{$event->title}}</h4><div class="d-flex flex-wrap gap-2"><span class="badge bg-label-primary">{{$event->type->name}}</span><span class="text-muted small"><i class="bx bx-calendar"></i> {{$event->start_date->translatedFormat('d M Y')}} - {{$event->end_date->translatedFormat('d M Y')}}</span></div></div><div class="d-flex gap-2"><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#minutesModal"><i class="bx bx-file me-1"></i>Berita Acara</button><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#importModal"><i class="bx bx-upload me-1"></i>Import Peserta</button></div></div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif
<div class="card border-primary mb-4"><div class="card-body"><label class="form-label fw-bold"><i class="bx bx-link me-1"></i>Link Publik Pengisian Biodata</label><div class="input-group"><input id="publicBiodataLink" class="form-control bg-light" readonly value="{{route('certifications.public',$event->public_token)}}"><button type="button" class="btn btn-outline-primary" onclick="navigator.clipboard.writeText(document.getElementById('publicBiodataLink').value);this.innerHTML='<i class=&quot;bx bx-check&quot;></i> Tersalin'"><i class="bx bx-copy me-1"></i>Salin Link</button><a href="{{route('certifications.public',$event->public_token)}}" target="_blank" class="btn btn-primary"><i class="bx bx-link-external me-1"></i>Buka</a></div><div class="form-text">Bagikan satu link ini kepada peserta. Peserta mengakses formulir menggunakan NIP/NIK hasil import.</div></div></div>
<div class="row g-3 mb-4">
 <div class="col-md-8"><div class="card h-100"><div class="card-body"><h6 class="fw-bold">Informasi Pelaksanaan</h6><div class="row g-3 small"><div class="col-sm-6"><span class="text-muted d-block">Lokasi</span><strong>{{$event->location}}</strong></div><div class="col-sm-6"><span class="text-muted d-block">Jumlah Peserta Direncanakan</span><strong>{{$event->participant_quota}} orang</strong></div><div class="col-sm-4"><span class="text-muted d-block">Pengawas</span><strong>{{$event->supervisor_name}}</strong></div><div class="col-sm-4"><span class="text-muted d-block">Nomor HP</span><strong>{{$event->supervisor_phone?:'-'}}</strong></div><div class="col-sm-4"><span class="text-muted d-block">Instansi Pengawas</span><strong>{{$event->supervisor_institution?:'-'}}</strong></div></div></div></div></div>
 <div class="col-md-4"><div class="card h-100 border-0 bg-label-{{$event->minutesFile?'success':'warning'}}"><div class="card-body"><h6 class="fw-bold">Berita Acara</h6>@if($event->minutesFile)<p class="small mb-2 text-truncate">{{$event->minutesFile->display_name}}</p><a href="{{route('documents.file.download',$event->minutesFile)}}" class="btn btn-sm btn-success"><i class="bx bx-download"></i> Download</a>@else<p class="small mb-0">Berita acara belum diunggah.</p>@endif</div></div></div>
</div>
<div class="card"><div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-2"><div><h5 class="mb-1">Peserta Sertifikasi</h5><small class="text-muted">{{$participants->total()}} peserta terdaftar</small></div>@if($participants->total()>0)<button type="button" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteAllParticipantsModal"><i class="bx bx-trash me-1"></i>Hapus Semua Peserta</button>@endif</div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Peserta</th><th>Jabatan & Instansi</th><th>Wilayah/Kontak</th><th>Riwayat</th><th style="min-width:210px">Status</th><th class="text-center">Aksi</th></tr></thead><tbody>
@forelse($participants as $p)@php $track=$attempts->get($p->nip_nik);@endphp<tr><td><strong>{{$p->name}}</strong><small class="d-block text-muted">{{$p->nip_nik}}</small>@if($p->biodata_file_id)<a href="{{route('documents.file.download',$p->biodata_file_id)}}" class="badge bg-label-success mt-2"><i class="bx bx-file me-1"></i>Biodata PDF</a>@elseif($p->biodata_submitted_at)<span class="badge bg-label-danger mt-2">PDF perlu dibuat ulang</span>@else<span class="badge bg-label-warning mt-2">Biodata belum diisi</span>@endif</td><td>{{$p->position?:'-'}}<small class="d-block text-muted">{{$p->institution?:'-'}}</small></td><td>{{$p->province?:'-'}} / {{$p->city?:'-'}}<small class="d-block text-muted">{{$p->phone?:$p->email}}</small></td><td><span class="badge bg-label-info">Percobaan ke-{{$track->attempts??1}}</span>@if(($track->failures??0)>0)<small class="d-block text-danger mt-1">{{$track->failures}}x tidak lulus</small>@endif</td><td><form method="POST" action="{{route('certifications.participants.result',$p)}}" class="d-flex gap-2">@csrf @method('PUT')<select name="result" class="form-select form-select-sm"><option value="belum_ditentukan" @selected($p->result==='belum_ditentukan')>Belum Ditentukan</option><option value="lulus" @selected($p->result==='lulus')>Lulus</option><option value="tidak_lulus" @selected($p->result==='tidak_lulus')>Tidak Lulus</option></select><button class="btn btn-sm btn-primary">Simpan</button></form></td><td class="text-center"><form method="POST" action="{{route('certifications.participants.destroy',$p)}}" onsubmit="return confirm('Hapus peserta {{$p->name}}? Biodata PDF, tanda tangan, status kelulusan, dan seluruh data peserta ini akan ikut dihapus secara permanen.')">@csrf @method('DELETE')<button type="submit" class="btn btn-sm btn-icon btn-outline-danger" title="Hapus peserta"><i class="bx bx-trash"></i></button></form></td></tr>
@empty<tr><td colspan="6" class="text-center py-5 text-muted">Belum ada peserta. Silakan import file Excel.</td></tr>@endforelse
</tbody></table></div>@if($participants->hasPages())<div class="card-footer">{{$participants->links()}}</div>@endif</div>

<div class="modal fade" id="deleteAllParticipantsModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 shadow-lg"><div class="modal-body text-center p-4 p-md-5"><span class="avatar-initial rounded-circle bg-label-danger d-inline-flex p-3 mb-3"><i class="bx bx-error-circle fs-1"></i></span><h4 class="fw-bold">Hapus Semua Peserta?</h4><p class="text-muted mb-3">Anda akan menghapus <strong>{{$participants->total()}} peserta</strong> dari kegiatan <strong>{{$event->title}}</strong>.</p><div class="alert alert-danger text-start small"><strong>Data yang ikut dihapus permanen:</strong><ul class="mb-0 mt-2 ps-3"><li>Identitas dan status kelulusan seluruh peserta</li><li>PDF biodata dan tanda tangan peserta</li><li>File Excel sumber import peserta</li></ul></div><p class="small text-muted">Berita acara dan data pelaksanaan sertifikasi tidak akan dihapus.</p><div class="d-flex justify-content-center gap-2 mt-4"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><form method="POST" action="{{route('certifications.participants.destroy-all',$event)}}">@csrf @method('DELETE')<button type="submit" class="btn btn-danger"><i class="bx bx-trash me-1"></i>Ya, Hapus Semua</button></form></div></div></div></div></div>
<div class="modal fade" id="importModal"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" enctype="multipart/form-data" action="{{route('certifications.import',$event)}}">@csrf<div class="modal-header"><h5 class="modal-title">Import Peserta</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-info small">NIP/NIK wajib diisi dan digunakan untuk mendeteksi peserta serta riwayat percobaan sertifikasi.</div><label class="form-label">File Excel</label><input type="file" name="file" accept=".xlsx,.xls" class="form-control" required></div><div class="modal-footer"><a href="{{route('certifications.template')}}" class="btn btn-outline-secondary"><i class="bx bx-download"></i> Template</a><button class="btn btn-primary">Import</button></div></form></div></div>
<div class="modal fade" id="minutesModal"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" enctype="multipart/form-data" action="{{route('certifications.minutes',$event)}}">@csrf<div class="modal-header"><h5 class="modal-title">Upload Berita Acara</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Dokumen PDF/Word</label><input type="file" name="file" accept=".pdf,.doc,.docx" class="form-control" required><div class="form-text">Maksimal 20 MB. Upload baru akan mengganti berita acara sebelumnya.</div></div><div class="modal-footer"><button class="btn btn-primary">Upload</button></div></form></div></div>
@endsection
