@extends('layouts.master')
@section('title','Kelola Sertifikat Pelatihan')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
 <div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4"><div><a href="{{route('trainings.manage',$training->id)}}" class="small"><i class="bx bx-left-arrow-alt"></i> Kembali ke Kelola Pelatihan</a><h4 class="fw-bold mt-2 mb-1">Kelola Sertifikat</h4><p class="text-muted mb-0">{{$training->nama_pelatihan}}</p></div><a href="{{route('training-certificates.template',$training)}}" class="btn btn-outline-primary align-self-lg-center"><i class="bx bx-download me-1"></i>Download Template + Kode</a></div>
 <div class="alert alert-info border-0"><i class="bx bx-file me-1"></i>Template tetap disusun dalam format DOCX. Saat generate, sistem otomatis mengonversi setiap sertifikat menjadi PDF dan mengemasnya dalam satu ZIP dengan nama file NIP/NIK peserta.</div>
 @if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
 @if($errors->any())<div class="alert alert-danger"><strong>Data belum dapat diproses.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
 <div class="row g-4 mb-4">
  <div class="col-xl-7"><div class="card h-100"><div class="card-header border-bottom"><h5 class="mb-1 fw-bold">1. Pengaturan Sertifikat</h5><small class="text-muted">Nomor yang sudah diberikan kepada peserta tidak akan berubah saat generate ulang.</small></div><div class="card-body">
   <form method="POST" enctype="multipart/form-data" action="{{route('training-certificates.setting',$training)}}" class="row g-3">@csrf
    <div class="col-md-6"><label class="form-label">Nama Sertifikat</label><input name="name" class="form-control" required value="{{old('name',$setting?->name?:'Sertifikat Pelatihan')}}"></div>
    <div class="col-md-4"><label class="form-label">Tanggal Penerbitan</label><input type="date" name="issued_at" class="form-control" required value="{{old('issued_at',$setting?->issued_at?->format('Y-m-d')?:now()->format('Y-m-d'))}}"></div>
    <div class="col-md-2"><label class="form-label">Ukuran Foto</label><select name="photo_size" class="form-select" required><option value="3x4" @selected(old('photo_size',$setting?->photo_size?:'3x4')==='3x4')>3 x 4 cm</option><option value="2x3" @selected(old('photo_size',$setting?->photo_size)==='2x3')>2 x 3 cm</option></select></div>
    <div class="col-md-9"><label class="form-label">Format Nomor Sertifikat</label><input name="number_format" class="form-control font-monospace" required value="{{old('number_format',$setting?->number_format?:'222.{X}/KPG.03.01.03/BPSDM/{TAHUN}')}}"><div class="form-text">Wajib memuat <code>{X}</code>. Gunakan <code>{X:3}</code> untuk 001, 002, 003.</div></div>
    <div class="col-md-3"><label class="form-label">Urutan Mulai</label><input type="number" min="0" name="start_sequence" class="form-control" required value="{{old('start_sequence',$setting?->start_sequence?:1)}}"></div>
    <div class="col-12"><label class="form-label">Template Word (.docx)</label><input type="file" name="template" accept=".docx" class="form-control" {{$setting?->template_path?'':'required'}}><div class="form-text">{{$setting?->template_path?'Template sudah tersedia. Pilih file hanya jika ingin mengganti.':'Template wajib diunggah sebelum generate.'}}</div></div>
    <div class="col-12"><button class="btn btn-primary"><i class="bx bx-save me-1"></i>Simpan Pengaturan</button></div>
   </form>
  </div></div></div>
  <div class="col-xl-5"><div class="card h-100"><div class="card-header border-bottom"><h5 class="fw-bold mb-1">Kode Template & Pratinjau</h5><small class="text-muted">Tempel kode berikut ke dokumen Word.</small></div><div class="card-body">
   <div class="d-flex flex-wrap gap-2 mb-3">@foreach(['${nama}','${nip_nik}','${jabatan}','${instansi}','${foto}','${nomor_sertifikat}','${nama_pelatihan}','${tanggal_mulai}','${tanggal_selesai}','${tanggal_sertifikat}'] as $code)<code class="border rounded px-2 py-1 bg-light">{{$code}}</code>@endforeach</div>
   <div class="alert alert-warning py-2 small"><i class="bx bx-image me-1"></i>Kode <code>${foto}</code> dipaksa ke ukuran 3x4 atau 2x3 cm. Foto dengan rasio berbeda akan ditarik mengikuti ukuran pilihan.</div>
   <h6 class="fw-bold">Contoh nomor pertama</h6><ol class="mb-0 ps-3">@foreach($preview as $number)<li class="font-monospace mb-1">{{$number}}</li>@endforeach</ol>
  </div></div></div>
 </div>
  <div class="card mb-4"><div class="card-header border-bottom d-flex flex-column flex-lg-row justify-content-between gap-3"><div><h5 class="fw-bold mb-1">2. Generate Sertifikat PDF</h5><small class="text-muted">Centang peserta atau biarkan kosong untuk menghasilkan seluruh peserta approved.</small></div>@if($setting?->template_path)<button form="generateForm" class="btn btn-primary"><i class="bx bx-package me-1"></i>Generate Bundel PDF (ZIP)</button>@endif</div>
  <form id="generateForm" method="POST" action="{{route('training-certificates.generate',$training)}}">@csrf</form><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th><input type="checkbox" class="form-check-input" id="checkAll"></th><th>Peserta</th><th>Data Template</th><th>Nomor Sertifikat</th><th>Status</th><th>Upload Final PDF</th></tr></thead><tbody>
   @forelse($participants as $p) @php($cert=$certificates->get($p->id))
   <tr><td><input type="checkbox" form="generateForm" class="form-check-input participant-check" name="participant_ids[]" value="{{$p->id}}"></td><td><strong>{{$p->name}}</strong><br><small class="text-muted">{{$p->nip_nik?:'NIP/NIK belum tersedia'}}</small></td><td><small>{{$p->jabatan?:$p->user?->jabatan?:'-'}}<br>{{$p->instansi?:$p->user?->instansi?:'-'}}</small><br><span class="badge bg-label-{{$p->pasFotoFile?'success':'warning'}}">Foto: {{$p->pasFotoFile?'Ada':'Belum ada'}}</span></td><td class="font-monospace small">{{$cert?->certificate_number?:'Belum ditetapkan'}}</td><td>@if($cert?->final_file_path)<span class="badge bg-success">Final tersedia</span>@elseif($cert?->generated_at)<span class="badge bg-label-info">Sudah generate</span>@else<span class="badge bg-label-secondary">Belum generate</span>@endif</td><td>@if($cert)<div class="d-flex gap-1"><form method="POST" enctype="multipart/form-data" action="{{route('training-certificates.final',$cert)}}" class="d-flex gap-1">@csrf<input type="file" name="certificate_file" accept=".pdf" class="form-control form-control-sm" required><button class="btn btn-sm btn-success">Upload</button></form>@if($cert->final_file_path)<a href="{{route('participant-certificates.download',$cert)}}" class="btn btn-sm btn-outline-primary"><i class="bx bx-download"></i></a>@endif</div>@else<small class="text-muted">Generate dahulu</small>@endif</td></tr>
   @empty<tr><td colspan="6" class="text-center text-muted py-5">Belum ada peserta approved.</td></tr>@endforelse
  </tbody></table></div>
 </div>
 <div class="card"><div class="card-header border-bottom"><h5 class="fw-bold mb-1">3. Upload Massal Sertifikat Final</h5><small class="text-muted">Unggah ZIP berisi PDF. Nama file wajib menggunakan NIP/NIK, contoh <code>198501012010011001.pdf</code>.</small></div><div class="card-body"><form method="POST" enctype="multipart/form-data" action="{{route('training-certificates.final-zip',$training)}}" class="row g-3 align-items-end">@csrf<div class="col-lg-9"><label class="form-label">Bundel ZIP Sertifikat Bertanda Tangan</label><input type="file" name="certificate_zip" accept=".zip" class="form-control" required></div><div class="col-lg-3"><button class="btn btn-success w-100"><i class="bx bx-cloud-upload me-1"></i>Cocokkan & Simpan</button></div></form></div></div>
</div>
@endsection
@push('js')<script>document.getElementById('checkAll')?.addEventListener('change',e=>document.querySelectorAll('.participant-check').forEach(c=>c.checked=e.target.checked));</script>@endpush
